/**
 * Version 1 draft, review, execution, browser-continuation and delivery tables.
 *
 * Invariants enforced here rather than in callers: an execution operation has exactly one parent
 * (draft XOR review intent); one open draft per participant and conversation; one open prompt per
 * conversation; one valid confirmation per subject; at most one unresolved attempt per operation;
 * grant budgets can never be over-reserved.
 */
export const WORKFLOW_TABLES: readonly string[] = [
  `CREATE TABLE work_drafts (
    id TEXT PRIMARY KEY,
    participant_id TEXT NOT NULL REFERENCES participants(id),
    conversation_id TEXT NOT NULL REFERENCES conversations(id),
    garden_chain_id INTEGER,
    garden_address TEXT,
    action_uid TEXT,
    revision INTEGER NOT NULL CHECK (revision >= 1),
    machine_snapshot TEXT NOT NULL,
    machine_version INTEGER NOT NULL,
    lifecycle TEXT NOT NULL CHECK (lifecycle IN ('open','published','cancelled','expired')),
    author_account_id TEXT REFERENCES account_bindings(id),
    last_participant_action_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    content_deleted_at INTEGER,
    CHECK ((garden_chain_id IS NULL) = (garden_address IS NULL))
  )`,
  `CREATE UNIQUE INDEX work_drafts_one_open
    ON work_drafts(participant_id, conversation_id) WHERE lifecycle = 'open'`,
  `CREATE TABLE draft_revisions (
    draft_id TEXT NOT NULL REFERENCES work_drafts(id),
    revision INTEGER NOT NULL CHECK (revision >= 1),
    content_ciphertext TEXT,
    content_digest TEXT NOT NULL,
    action_definition_digest TEXT,
    action_definition_snapshot TEXT,
    evidence_manifest TEXT NOT NULL DEFAULT '[]',
    cause TEXT NOT NULL,
    source_event_id TEXT REFERENCES inbox_events(id),
    created_at INTEGER NOT NULL,
    PRIMARY KEY (draft_id, revision)
  )`,
  `CREATE TABLE conversation_prompts (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations(id),
    participant_id TEXT REFERENCES participants(id),
    channel_subject_id TEXT NOT NULL REFERENCES channel_subjects(id),
    subject_kind TEXT NOT NULL
      CHECK (subject_kind IN ('consent','draft','review','pairing','recovery')),
    subject_id TEXT,
    subject_revision INTEGER,
    kind TEXT NOT NULL,
    field_key TEXT,
    token TEXT NOT NULL,
    options_json TEXT NOT NULL DEFAULT '[]',
    page INTEGER NOT NULL DEFAULT 0,
    state TEXT NOT NULL CHECK (state IN ('open','answered','superseded','expired')),
    created_at INTEGER NOT NULL,
    resolved_at INTEGER
  )`,
  `CREATE UNIQUE INDEX conversation_prompts_one_open
    ON conversation_prompts(conversation_id) WHERE state = 'open'`,
  `CREATE TABLE media_assets (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations(id),
    participant_id TEXT REFERENCES participants(id),
    draft_id TEXT REFERENCES work_drafts(id),
    source_entry_id TEXT NOT NULL REFERENCES source_entries(id),
    ordinal INTEGER NOT NULL,
    provider_ref_ciphertext TEXT,
    declared_mime TEXT,
    private_object_ciphertext TEXT,
    source_digest TEXT,
    source_size INTEGER,
    detected_type TEXT,
    sanitized_object_ciphertext TEXT,
    sanitized_digest TEXT,
    sanitized_mime TEXT,
    asset_kind TEXT NOT NULL
      CHECK (asset_kind IN ('image','pdf','docx','xlsx','csv','audio','video','unsupported')),
    processing_manifest TEXT NOT NULL DEFAULT '{}',
    state TEXT NOT NULL CHECK (state IN ('received','quarantined','inspecting','converting',
      'extracting','ready','needs_clarification','failed','unsupported','deleted')),
    public_cid TEXT,
    public_revision INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    deleted_at INTEGER,
    UNIQUE (source_entry_id, ordinal)
  )`,
  `CREATE TABLE work_records (
    chain_id INTEGER NOT NULL,
    work_uid TEXT NOT NULL,
    draft_id TEXT REFERENCES work_drafts(id),
    garden_address TEXT NOT NULL,
    action_uid TEXT NOT NULL,
    attester TEXT NOT NULL,
    transaction_hash TEXT,
    published_revision INTEGER,
    observed_at INTEGER NOT NULL,
    PRIMARY KEY (chain_id, work_uid)
  )`,
  `CREATE TABLE review_intents (
    id TEXT PRIMARY KEY,
    chain_id INTEGER NOT NULL,
    work_uid TEXT NOT NULL,
    participant_id TEXT NOT NULL REFERENCES participants(id),
    conversation_id TEXT NOT NULL REFERENCES conversations(id),
    steward_account_id TEXT NOT NULL REFERENCES account_bindings(id),
    revision INTEGER NOT NULL CHECK (revision >= 1),
    content_ciphertext TEXT,
    content_digest TEXT NOT NULL,
    history_ciphertext TEXT,
    machine_snapshot TEXT NOT NULL,
    machine_version INTEGER NOT NULL,
    lifecycle TEXT NOT NULL CHECK (lifecycle IN ('open','recorded','cancelled')),
    expected_decision_sequence INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (chain_id, work_uid) REFERENCES work_records(chain_id, work_uid)
  )`,
  `CREATE UNIQUE INDEX review_intents_one_open
    ON review_intents(chain_id, work_uid, steward_account_id) WHERE lifecycle = 'open'`,
  `CREATE TABLE confirmations (
    id TEXT PRIMARY KEY,
    draft_id TEXT REFERENCES work_drafts(id),
    review_intent_id TEXT REFERENCES review_intents(id),
    revision INTEGER NOT NULL,
    summary_digest TEXT NOT NULL,
    content_digest TEXT NOT NULL,
    action_definition_digest TEXT,
    account_binding_id TEXT REFERENCES account_bindings(id),
    garden_chain_id INTEGER NOT NULL,
    garden_address TEXT NOT NULL,
    source_event_id TEXT NOT NULL REFERENCES inbox_events(id),
    prompt_id TEXT NOT NULL REFERENCES conversation_prompts(id),
    identity_epoch INTEGER NOT NULL,
    publication_consent_id TEXT REFERENCES consent_records(id),
    confirmed_at INTEGER NOT NULL,
    invalidated_at INTEGER,
    CHECK ((draft_id IS NULL) <> (review_intent_id IS NULL))
  )`,
  `CREATE UNIQUE INDEX confirmations_one_valid_draft
    ON confirmations(draft_id) WHERE draft_id IS NOT NULL AND invalidated_at IS NULL`,
  `CREATE UNIQUE INDEX confirmations_one_valid_review
    ON confirmations(review_intent_id) WHERE review_intent_id IS NOT NULL AND invalidated_at IS NULL`,
  `CREATE TABLE execution_grants (
    id TEXT PRIMARY KEY,
    purpose TEXT NOT NULL CHECK (purpose IN ('reporting','review')),
    participant_id TEXT NOT NULL REFERENCES participants(id),
    account_binding_id TEXT NOT NULL REFERENCES account_bindings(id),
    channel_binding_id TEXT NOT NULL REFERENCES channel_bindings(id),
    identity_epoch INTEGER NOT NULL,
    chain_id INTEGER NOT NULL,
    garden_address TEXT NOT NULL,
    module_ref TEXT NOT NULL,
    permission_id TEXT,
    signer_key_ref TEXT NOT NULL,
    signer_address TEXT NOT NULL,
    policy_digest TEXT NOT NULL,
    policy_json TEXT NOT NULL,
    revocation_descriptor TEXT,
    approval_ciphertext TEXT,
    valid_after INTEGER NOT NULL,
    valid_until INTEGER NOT NULL CHECK (valid_until > valid_after),
    max_submissions INTEGER NOT NULL CHECK (max_submissions >= 1),
    submissions_reserved INTEGER NOT NULL DEFAULT 0 CHECK (submissions_reserved >= 0),
    submissions_consumed INTEGER NOT NULL DEFAULT 0 CHECK (submissions_consumed >= 0),
    gas_cap INTEGER NOT NULL CHECK (gas_cap >= 0),
    gas_reserved INTEGER NOT NULL DEFAULT 0 CHECK (gas_reserved >= 0),
    gas_consumed INTEGER NOT NULL DEFAULT 0 CHECK (gas_consumed >= 0),
    version INTEGER NOT NULL DEFAULT 1,
    state TEXT NOT NULL CHECK (state IN ('proposed','owner_authorization_pending','enabling',
      'reconciling_setup','active','paused','expired','revocation_pending',
      'reconciling_revocation','revoked','failed')),
    enable_reference TEXT,
    revoke_reference TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    CHECK (submissions_reserved + submissions_consumed <= max_submissions),
    CHECK (gas_reserved + gas_consumed <= gas_cap)
  )`,
  `CREATE UNIQUE INDEX execution_grants_one_live
    ON execution_grants(account_binding_id, purpose, chain_id, garden_address)
    WHERE state IN ('proposed','owner_authorization_pending','enabling','reconciling_setup',
      'active','paused')`,
  `CREATE TABLE execution_operations (
    id TEXT PRIMARY KEY,
    logical_operation_key TEXT NOT NULL UNIQUE,
    kind TEXT NOT NULL CHECK (kind IN ('work','review')),
    draft_id TEXT REFERENCES work_drafts(id),
    review_intent_id TEXT REFERENCES review_intents(id),
    author_account_id TEXT NOT NULL REFERENCES account_bindings(id),
    resource_revision INTEGER NOT NULL,
    confirmation_id TEXT NOT NULL REFERENCES confirmations(id),
    chain_id INTEGER NOT NULL,
    garden_address TEXT NOT NULL,
    authorization_mode TEXT CHECK (authorization_mode IN ('owner','delegated')),
    payload_digest TEXT,
    prepared_envelope_ciphertext TEXT,
    attempt_version INTEGER NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 1,
    state TEXT NOT NULL CHECK (state IN ('created','preparing','preparation_failed','prepared',
      'sending','reconciling','published','failed','cancelled')),
    failure_code TEXT,
    transaction_hash TEXT,
    attestation_uid TEXT,
    block_hash TEXT,
    log_index INTEGER,
    from_block INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    CHECK ((draft_id IS NULL) <> (review_intent_id IS NULL)),
    CHECK ((kind = 'work') = (draft_id IS NOT NULL))
  )`,
  `CREATE TABLE execution_attempts (
    id TEXT PRIMARY KEY,
    operation_id TEXT NOT NULL REFERENCES execution_operations(id),
    attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1),
    authorization_mode TEXT NOT NULL CHECK (authorization_mode IN ('owner','delegated')),
    execution_grant_id TEXT REFERENCES execution_grants(id),
    policy_digest TEXT,
    payload_digest TEXT NOT NULL,
    identity_epoch INTEGER NOT NULL,
    expected_account TEXT NOT NULL,
    from_block INTEGER,
    nonce_ref TEXT,
    signed_operation_ciphertext TEXT,
    user_operation_hash TEXT,
    transaction_hash TEXT,
    gas_reserved INTEGER NOT NULL DEFAULT 0,
    state TEXT NOT NULL CHECK (state IN ('reserved','wallet_pending','signed','broadcast',
      'uncertain','rejected_before_send','preparation_failed','released','confirmed','reverted')),
    reason_code TEXT,
    submitted_at INTEGER,
    resolved_at INTEGER,
    observed_block_hash TEXT,
    attested_log_index INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (operation_id, attempt_number),
    CHECK ((authorization_mode = 'delegated') = (execution_grant_id IS NOT NULL))
  )`,
  `CREATE UNIQUE INDEX execution_attempts_one_unresolved ON execution_attempts(operation_id)
    WHERE state IN ('reserved','wallet_pending','signed','broadcast','uncertain')`,
  `CREATE TABLE attempt_outcomes (
    attempt_id TEXT NOT NULL REFERENCES execution_attempts(id),
    idempotency_key TEXT NOT NULL,
    request_digest TEXT NOT NULL,
    outcome_kind TEXT NOT NULL,
    response_json TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    PRIMARY KEY (attempt_id, idempotency_key)
  )`,
];
