
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// 🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑

/* eslint-disable */
export type CoercedEnvSchema = {
  /** **APP_ENV** 🔐 _sensitive_ */
  APP_ENV?: "development" | "test" | "staging" | "production";
  
  /**
   * **OP_ENABLE_ENVIRONMENT_LOAD** 🔐 _sensitive_  
   * 1Password integration  
   * Keep bulk environment loading off for stable local CLI usage.  
   */
  OP_ENABLE_ENVIRONMENT_LOAD?: boolean;
  
  /**
   * **OP_SERVICE_ACCOUNT_TOKEN** 🔐 _sensitive_  
   * Service account token used in CI/deployed environments.  
   * Optional locally if you prefer service-account auth over desktop app auth.  
   *   
   * 📚 {@link https://developer.1password.com/docs/service-accounts/ | 1Password service accounts}  
   * 📚 {@link https://example.com}  
   */
  OP_SERVICE_ACCOUNT_TOKEN?: string;
  
  /**
   * **OP_ACCOUNT** 🔐 _sensitive_  
   * Optional 1Password account shorthand/id for the `op` CLI when multiple  
   * accounts are configured locally.  
   */
  OP_ACCOUNT?: string;
  
  /**
   * **OP_ENVIRONMENT** 🔐 _sensitive_  
   * Optional 1Password environment ID/name for bulk secret injection. This is  
   * ignored unless OP_ENABLE_ENVIRONMENT_LOAD=true.  
   */
  OP_ENVIRONMENT?: string;
  
  /**
   * **WALLETCONNECT_PROJECT_ID_OP_REF** 🔐 _sensitive_  
   * Optional local 1Password secret reference for standard `op` CLI installs.  
   * Example: WALLETCONNECT_PROJECT_ID_OP_REF=op://GreenGoods/VITE_WALLETCONNECT_PROJECT_ID/credential  
   */
  WALLETCONNECT_PROJECT_ID_OP_REF?: string;
  
  /** **VITE_WALLETCONNECT_PROJECT_ID** */
  VITE_WALLETCONNECT_PROJECT_ID?: string;
  
  /**
   * **PIMLICO_API_KEY_OP_REF** 🔐 _sensitive_  
   * Optional local 1Password secret reference for standard `op` CLI installs.  
   */
  PIMLICO_API_KEY_OP_REF?: string;
  
  /** **VITE_PIMLICO_API_KEY** */
  VITE_PIMLICO_API_KEY?: string;
  
  /** **VITE_PASSKEY_RP_ID** */
  VITE_PASSKEY_RP_ID?: string;
  
  /** **VITE_CHAIN_ID** */
  VITE_CHAIN_ID?: number;
  
  /**
   * **ALCHEMY_API_KEY_OP_REF** 🔐 _sensitive_  
   * Optional local 1Password secret reference for standard `op` CLI installs.  
   */
  ALCHEMY_API_KEY_OP_REF?: string;
  
  /** **ALCHEMY_API_KEY** 🔐 _sensitive_ */
  ALCHEMY_API_KEY?: string;
  
  /**
   * **VITE_ALCHEMY_API_KEY**  
   * Aliases used by some scripts.  
   */
  VITE_ALCHEMY_API_KEY?: string;
  
  /** **ALCHEMY_KEY** 🔐 _sensitive_ */
  ALCHEMY_KEY?: string;
  
  /** **ARBITRUM_RPC_URL** 🔐 _sensitive_ */
  ARBITRUM_RPC_URL?: string;
  
  /** **CELO_RPC_URL** 🔐 _sensitive_ */
  CELO_RPC_URL?: string;
  
  /** **ETHEREUM_RPC_URL** 🔐 _sensitive_ */
  ETHEREUM_RPC_URL?: string;
  
  /** **SEPOLIA_RPC_URL** 🔐 _sensitive_ */
  SEPOLIA_RPC_URL?: string;
  
  /** **OPTIMISM_RPC_URL** 🔐 _sensitive_ */
  OPTIMISM_RPC_URL?: string;
  
  /**
   * **ARBITRUM_FORK_RPC_URL** 🔐 _sensitive_  
   * Optional high-capacity overrides for Foundry fork tests.  
   * Prefer dedicated provider URLs here when public endpoints start rate-limiting.  
   */
  ARBITRUM_FORK_RPC_URL?: string;
  
  /** **SEPOLIA_FORK_RPC_URL** 🔐 _sensitive_ */
  SEPOLIA_FORK_RPC_URL?: string;
  
  /** **CELO_FORK_RPC_URL** 🔐 _sensitive_ */
  CELO_FORK_RPC_URL?: string;
  
  /**
   * **ARBITRUM_FORK_BLOCK_NUMBER** 🔐 _sensitive_  
   * Optional fork pins for deterministic reruns against live chains.  
   */
  ARBITRUM_FORK_BLOCK_NUMBER?: string;
  
  /** **SEPOLIA_FORK_BLOCK_NUMBER** 🔐 _sensitive_ */
  SEPOLIA_FORK_BLOCK_NUMBER?: string;
  
  /** **CELO_FORK_BLOCK_NUMBER** 🔐 _sensitive_ */
  CELO_FORK_BLOCK_NUMBER?: string;
  
  /** **FOUNDRY_KEYSTORE_ACCOUNT** 🔐 _sensitive_ */
  FOUNDRY_KEYSTORE_ACCOUNT?: string;
  
  /**
   * **ETHERSCAN_API_KEY_OP_REF** 🔐 _sensitive_  
   * Optional local 1Password secret reference for standard `op` CLI installs.  
   */
  ETHERSCAN_API_KEY_OP_REF?: string;
  
  /** **ETHERSCAN_API_KEY** 🔐 _sensitive_ */
  ETHERSCAN_API_KEY?: string;
  
  /** **DEPLOYMENT_SALT** 🔐 _sensitive_ */
  DEPLOYMENT_SALT?: string;
  
  /** **ENS_L1_RECEIVER** 🔐 _sensitive_ */
  ENS_L1_RECEIVER?: string;
  
  /** **COMMUNITY_GARDEN_SLUG** 🔐 _sensitive_ */
  COMMUNITY_GARDEN_SLUG?: string;
  
  /** **AUTO_DEPLOY_OCTANT_FACTORY** 🔐 _sensitive_ */
  AUTO_DEPLOY_OCTANT_FACTORY?: boolean;
  
  /** **REQUIRE_OCTANT_READY** 🔐 _sensitive_ */
  REQUIRE_OCTANT_READY?: boolean;
  
  /** **REQUIRE_COOKIEJAR_READY** 🔐 _sensitive_ */
  REQUIRE_COOKIEJAR_READY?: boolean;
  
  /** **DEPLOYMENT_OUTPUT_DIR** 🔐 _sensitive_ */
  DEPLOYMENT_OUTPUT_DIR?: string;
  
  /** **UPDATE_SCHEMAS_ONLY** 🔐 _sensitive_ */
  UPDATE_SCHEMAS_ONLY?: boolean;
  
  /** **FORCE_REDEPLOY** 🔐 _sensitive_ */
  FORCE_REDEPLOY?: boolean;
  
  /** **GG_CONTRACTS_BUILD_MODE** 🔐 _sensitive_ */
  GG_CONTRACTS_BUILD_MODE?: "auto" | "fast" | "full";
  
  /** **GG_CONTRACTS_BUILD_QUIET** 🔐 _sensitive_ */
  GG_CONTRACTS_BUILD_QUIET?: boolean;
  
  /** **DEPLOYMENT_REGISTRY_ALLOWLIST** 🔐 _sensitive_ */
  DEPLOYMENT_REGISTRY_ALLOWLIST?: string;
  
  /** **HATS_MODULE** 🔐 _sensitive_ */
  HATS_MODULE?: string;
  
  /**
   * **PINATA_JWT_OP_REF** 🔐 _sensitive_  
   * Replace the item and field names only if your 1Password vault differs.  
   */
  PINATA_JWT_OP_REF?: string;
  
  /** **PINATA_JWT** 🔐 _sensitive_ */
  PINATA_JWT?: string;
  
  /** **PINATA_GATEWAY_URL** 🔐 _sensitive_ */
  PINATA_GATEWAY_URL?: string;
  
  /** **PINATA_API_URL** 🔐 _sensitive_ */
  PINATA_API_URL?: string;
  
  /** **PINATA_UPLOADS_API_URL** 🔐 _sensitive_ */
  PINATA_UPLOADS_API_URL?: string;
  
  /**
   * **VITE_PINATA_GATEWAY_URL**  
   * Browser-facing read config. Upload authority stays on the agent.  
   */
  VITE_PINATA_GATEWAY_URL?: string;
  
  /**
   * **GARDENS_SUBGRAPH_KEY_OP_REF** 🔐 _sensitive_  
   * Optional local 1Password secret reference for standard `op` CLI installs.  
   */
  GARDENS_SUBGRAPH_KEY_OP_REF?: string;
  
  /** **VITE_ENVIO_INDEXER_URL** */
  VITE_ENVIO_INDEXER_URL?: string;
  
  /**
   * **VITE_GARDENS_SUBGRAPH_KEY**  
   * NOTE: currently consumed in browser-side shared config.  
   */
  VITE_GARDENS_SUBGRAPH_KEY?: string;
  
  /**
   * **POSTHOG_AGENT_KEY_OP_REF** 🔐 _sensitive_  
   * Optional local 1Password secret references for standard `op` CLI installs.  
   */
  POSTHOG_AGENT_KEY_OP_REF?: string;
  
  /** **POSTHOG_KEY_OP_REF** 🔐 _sensitive_ */
  POSTHOG_KEY_OP_REF?: string;
  
  /** **POSTHOG_ADMIN_KEY_OP_REF** 🔐 _sensitive_ */
  POSTHOG_ADMIN_KEY_OP_REF?: string;
  
  /** **POSTHOG_AGENT_KEY** 🔐 _sensitive_ */
  POSTHOG_AGENT_KEY?: string;
  
  /** **VITE_POSTHOG_KEY** */
  VITE_POSTHOG_KEY?: string;
  
  /** **VITE_POSTHOG_ADMIN_KEY** */
  VITE_POSTHOG_ADMIN_KEY?: string;
  
  /** **VITE_POSTHOG_DEBUG** */
  VITE_POSTHOG_DEBUG?: boolean;
  
  /** **ANALYTICS_ENABLED** 🔐 _sensitive_ */
  ANALYTICS_ENABLED?: boolean;
  
  /** **VITE_APP_VERSION** */
  VITE_APP_VERSION?: string;
  
  /** **VITE_APP_URL** */
  VITE_APP_URL?: string;
  
  /** **VITE_CLIENT_APP_URL** */
  VITE_CLIENT_APP_URL?: string;
  
  /** **VITE_API_BASE_URL** */
  VITE_API_BASE_URL?: string;
  
  /** **VITE_GOOGLE_APPOINTMENT_URL** */
  VITE_GOOGLE_APPOINTMENT_URL?: string;
  
  /** **VITE_THIRDWEB_CLIENT_ID** */
  VITE_THIRDWEB_CLIENT_ID?: string;
  
  /** **VITE_ENABLE_SW_DEV** */
  VITE_ENABLE_SW_DEV?: boolean;
  
  /** **VITE_ENABLE_RPC_BG_SYNC** */
  VITE_ENABLE_RPC_BG_SYNC?: boolean;
  
  /** **VITE_DEBUG_MODE** */
  VITE_DEBUG_MODE?: boolean;
  
  /** **VITE_QUEUE_DEBUG** */
  VITE_QUEUE_DEBUG?: boolean;
  
  /** **VITE_MOCK_PWA_INSTALLED** */
  VITE_MOCK_PWA_INSTALLED?: boolean;
  
  /**
   * **VITE_PIMLICO_SPONSORSHIP_POLICY_ID**  
   * Optional Pimlico policy override for sponsored transactions.  
   */
  VITE_PIMLICO_SPONSORSHIP_POLICY_ID?: string;
  
  /**
   * **VITE_ERC7677_PROXY_URL**  
   * Optional ERC-7677 paymaster proxy URL for gas sponsorship.  
   */
  VITE_ERC7677_PROXY_URL?: string;
  
  /** **VITE_USE_HASH_ROUTER** */
  VITE_USE_HASH_ROUTER?: boolean;
  
  /**
   * **TELEGRAM_BOT_TOKEN_OP_REF** 🔐 _sensitive_  
   * Optional local 1Password secret references for standard `op` CLI installs.  
   */
  TELEGRAM_BOT_TOKEN_OP_REF?: string;
  
  /** **ENCRYPTION_SECRET_OP_REF** 🔐 _sensitive_ */
  ENCRYPTION_SECRET_OP_REF?: string;
  
  /** **TELEGRAM_WEBHOOK_SECRET_OP_REF** 🔐 _sensitive_ */
  TELEGRAM_WEBHOOK_SECRET_OP_REF?: string;
  
  /** **LUMA_API_KEY_OP_REF** 🔐 _sensitive_ */
  LUMA_API_KEY_OP_REF?: string;
  
  /** **THIRDWEB_SECRET_KEY_OP_REF** 🔐 _sensitive_ */
  THIRDWEB_SECRET_KEY_OP_REF?: string;
  
  /** **THIRDWEB_WEBHOOK_SECRET_OP_REF** 🔐 _sensitive_ */
  THIRDWEB_WEBHOOK_SECRET_OP_REF?: string;
  
  /** **TELEGRAM_BOT_TOKEN** 🔐 _sensitive_ */
  TELEGRAM_BOT_TOKEN?: string;
  
  /** **ENCRYPTION_SECRET** 🔐 _sensitive_ */
  ENCRYPTION_SECRET?: string;
  
  /** **BOT_MODE** 🔐 _sensitive_ */
  BOT_MODE?: "polling" | "webhook";
  
  /** **PORT** 🔐 _sensitive_ */
  PORT?: number;
  
  /** **HOST** 🔐 _sensitive_ */
  HOST?: string;
  
  /** **WEBHOOK_URL** 🔐 _sensitive_ */
  WEBHOOK_URL?: string;
  
  /** **TELEGRAM_WEBHOOK_SECRET** 🔐 _sensitive_ */
  TELEGRAM_WEBHOOK_SECRET?: string;
  
  /** **DB_PATH** 🔐 _sensitive_ */
  DB_PATH?: string;
  
  /** **LOG_LEVEL** 🔐 _sensitive_ */
  LOG_LEVEL?: string;
  
  /** **BOT_API_TOKEN** 🔐 _sensitive_ */
  BOT_API_TOKEN?: string;
  
  /** **LUMA_API_KEY** 🔐 _sensitive_ */
  LUMA_API_KEY?: string;
  
  /** **LUMA_CALENDAR_ID** 🔐 _sensitive_ */
  LUMA_CALENDAR_ID?: string;
  
  /** **LUMA_GREEN_GOODS_TAG_ID** 🔐 _sensitive_ */
  LUMA_GREEN_GOODS_TAG_ID?: string;
  
  /** **LUMA_GREEN_GOODS_TAG_NAME** 🔐 _sensitive_ */
  LUMA_GREEN_GOODS_TAG_NAME?: string;
  
  /** **THIRDWEB_SECRET_KEY** 🔐 _sensitive_ */
  THIRDWEB_SECRET_KEY?: string;
  
  /** **THIRDWEB_WEBHOOK_SECRET** 🔐 _sensitive_ */
  THIRDWEB_WEBHOOK_SECRET?: string;
  
  /** **AGENT_ALLOWED_ORIGINS** 🔐 _sensitive_ */
  AGENT_ALLOWED_ORIGINS?: string;
  
  /**
   * **AGENT_PUBLIC_ALLOWED_ORIGINS** 🔐 _sensitive_  
   * Compatibility alias for existing public routes.  
   */
  AGENT_PUBLIC_ALLOWED_ORIGINS?: string;
  
  /** **AGENT_TRUSTED_PROXY_HOPS** 🔐 _sensitive_ */
  AGENT_TRUSTED_PROXY_HOPS?: number;
  
  /** **AGENT_TRUSTED_PROXY_CIDRS** 🔐 _sensitive_ */
  AGENT_TRUSTED_PROXY_CIDRS?: string;
  
  /** **AGENT_UPLOAD_SIGN_TTL_SECONDS** 🔐 _sensitive_ */
  AGENT_UPLOAD_SIGN_TTL_SECONDS?: number;
  
  /** **AGENT_UPLOAD_MAX_FILE_SIZE_BYTES** 🔐 _sensitive_ */
  AGENT_UPLOAD_MAX_FILE_SIZE_BYTES?: number;
  
  /** **AGENT_UPLOAD_ALLOWED_MIME_TYPES** 🔐 _sensitive_ */
  AGENT_UPLOAD_ALLOWED_MIME_TYPES?: string;
  
  /** **AGENT_UPLOAD_SIGN_RATE_LIMIT** 🔐 _sensitive_ */
  AGENT_UPLOAD_SIGN_RATE_LIMIT?: number;
  
  /** **AGENT_UPLOAD_SIGN_RATE_LIMIT_WINDOW_MS** 🔐 _sensitive_ */
  AGENT_UPLOAD_SIGN_RATE_LIMIT_WINDOW_MS?: number;
  
  /** **NODE_ENV** 🔐 _sensitive_ */
  NODE_ENV?: "development" | "test" | "production";
  
  /** **CI** 🔐 _sensitive_ */
  CI?: boolean;
  
  /** **DEVCONTAINER** 🔐 _sensitive_ */
  DEVCONTAINER?: boolean;
  
  /** **SKIP_MKCERT** 🔐 _sensitive_ */
  SKIP_MKCERT?: boolean;
  
  /** **SKIP_WEBSERVER** 🔐 _sensitive_ */
  SKIP_WEBSERVER?: boolean;
  
  /** **SKIP_HEALTH_CHECK** 🔐 _sensitive_ */
  SKIP_HEALTH_CHECK?: boolean;
  
  /** **ENABLE_PWA_E2E** 🔐 _sensitive_ */
  ENABLE_PWA_E2E?: boolean;
  
  /** **RUN_REAL_PASSKEY_E2E** 🔐 _sensitive_ */
  RUN_REAL_PASSKEY_E2E?: boolean;
  
  /** **TESTNET** 🔐 _sensitive_ */
  TESTNET?: boolean;
  
  /** **ANVIL_FORK_BLOCK** 🔐 _sensitive_ */
  ANVIL_FORK_BLOCK?: number;
  
  /** **ANVIL_RUNNING** 🔐 _sensitive_ */
  ANVIL_RUNNING?: boolean;
  
  /** **VITE_RPC_URL_11155111** */
  VITE_RPC_URL_11155111?: string;
  
  /**
   * **CONTRACT_REALISM_MODE** 🔐 _sensitive_  
   * Contract test realism tooling.  
   */
  CONTRACT_REALISM_MODE?: string;
  
  /** **CONTRACT_REALISM_REPORT_MD** 🔐 _sensitive_ */
  CONTRACT_REALISM_REPORT_MD?: string;
  
  /** **CONTRACT_REALISM_REPORT_JSON** 🔐 _sensitive_ */
  CONTRACT_REALISM_REPORT_JSON?: string;
  
  /**
   * **CHECK_INDEXER_RUNTIME** 🔐 _sensitive_  
   * Post-deploy verification toggles.  
   */
  CHECK_INDEXER_RUNTIME?: boolean;
  
  /** **POST_DEPLOY_INDEXER_URL** 🔐 _sensitive_ */
  POST_DEPLOY_INDEXER_URL?: string;
  
  /** **INDEXER_SYNC_TIMEOUT_SECONDS** 🔐 _sensitive_ */
  INDEXER_SYNC_TIMEOUT_SECONDS?: number;
  
  /** **INDEXER_SYNC_POLL_SECONDS** 🔐 _sensitive_ */
  INDEXER_SYNC_POLL_SECONDS?: number;
  
  /** **LOCALHOST_RPC_URL** 🔐 _sensitive_ */
  LOCALHOST_RPC_URL: string;
  
  /** **BASE_SEPOLIA_RPC_URL** 🔐 _sensitive_ */
  BASE_SEPOLIA_RPC_URL: string;
  
  /**
   * **ENS_PARENT_NAME** 🔐 _sensitive_  
   * ENS  
   */
  ENS_PARENT_NAME: string;
  
  /** **ENS_RESOLVER_ADDRESS** 🔐 _sensitive_ */
  ENS_RESOLVER_ADDRESS: string;
  
  /** **VITE_DESKTOP_DEV** 🔐 _sensitive_ */
  VITE_DESKTOP_DEV: boolean;
  
  /** **MCP_SERVER_PORT** 🔐 _sensitive_ */
  MCP_SERVER_PORT: number;
  
  /** **POSTHOG_ANALYTICS_READ_KEY** 🔐 _sensitive_ */
  POSTHOG_ANALYTICS_READ_KEY: string;
  
};


declare module 'varlock/env' {
  export interface TypedEnvSchema extends Readonly<CoercedEnvSchema> {}
  export interface PublicTypedEnvSchema extends Readonly<Pick<CoercedEnvSchema, 'VITE_WALLETCONNECT_PROJECT_ID' | 'VITE_PIMLICO_API_KEY' | 'VITE_PASSKEY_RP_ID' | 'VITE_CHAIN_ID' | 'VITE_ALCHEMY_API_KEY' | 'VITE_PINATA_GATEWAY_URL' | 'VITE_ENVIO_INDEXER_URL' | 'VITE_GARDENS_SUBGRAPH_KEY' | 'VITE_POSTHOG_KEY' | 'VITE_POSTHOG_ADMIN_KEY' | 'VITE_POSTHOG_DEBUG' | 'VITE_APP_VERSION' | 'VITE_APP_URL' | 'VITE_CLIENT_APP_URL' | 'VITE_API_BASE_URL' | 'VITE_GOOGLE_APPOINTMENT_URL' | 'VITE_THIRDWEB_CLIENT_ID' | 'VITE_ENABLE_SW_DEV' | 'VITE_ENABLE_RPC_BG_SYNC' | 'VITE_DEBUG_MODE' | 'VITE_QUEUE_DEBUG' | 'VITE_MOCK_PWA_INSTALLED' | 'VITE_PIMLICO_SPONSORSHIP_POLICY_ID' | 'VITE_ERC7677_PROXY_URL' | 'VITE_USE_HASH_ROUTER' | 'VITE_RPC_URL_11155111'>> {}
}


export type EnvSchemaAsStrings = {
  [Property in keyof CoercedEnvSchema]:
    CoercedEnvSchema[Property] extends string ? CoercedEnvSchema[Property]
      : (CoercedEnvSchema[Property] extends boolean ? ('true' | 'false') : string)
};

declare global {

  // add types for global import.meta.env
  interface ImportMetaEnv extends EnvSchemaAsStrings {}
  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }

  // add types for global process.env
  namespace NodeJS {
    interface ProcessEnv extends EnvSchemaAsStrings {}
  }
}