import type { queryKeys } from "./registry";

export type QueryKey =
  | typeof queryKeys.all
  | ReturnType<typeof queryKeys.queue.stats>
  | ReturnType<typeof queryKeys.queue.jobs>
  | ReturnType<typeof queryKeys.queue.pendingCount>
  | typeof queryKeys.works.all
  | ReturnType<typeof queryKeys.works.online>
  | ReturnType<typeof queryKeys.works.offline>
  | ReturnType<typeof queryKeys.works.merged>
  | ReturnType<typeof queryKeys.works.approvals>
  | typeof queryKeys.workApprovals.all
  | ReturnType<typeof queryKeys.workApprovals.byAttester>
  | ReturnType<typeof queryKeys.workApprovals.offline>
  | typeof queryKeys.offline.all
  | ReturnType<typeof queryKeys.offline.status>
  | ReturnType<typeof queryKeys.offline.sync>
  | typeof queryKeys.media.all
  | ReturnType<typeof queryKeys.media.forJob>
  | typeof queryKeys.hypercerts.all
  | ReturnType<typeof queryKeys.hypercerts.attestations>
  | ReturnType<typeof queryKeys.hypercerts.list>
  | ReturnType<typeof queryKeys.hypercerts.detail>
  | ReturnType<typeof queryKeys.hypercerts.drafts>
  | typeof queryKeys.vaults.all
  | ReturnType<typeof queryKeys.vaults.byChain>
  | ReturnType<typeof queryKeys.vaults.byGarden>
  | ReturnType<typeof queryKeys.vaults.deposits>
  | ReturnType<typeof queryKeys.vaults.myDeposits>
  | ReturnType<typeof queryKeys.vaults.events>
  | ReturnType<typeof queryKeys.vaults.preview>
  | ReturnType<typeof queryKeys.vaults.allDeposits>
  | typeof queryKeys.platform.all
  | ReturnType<typeof queryKeys.platform.stats>
  | typeof queryKeys.public.all
  | ReturnType<typeof queryKeys.public.gardens>
  | ReturnType<typeof queryKeys.public.gardenDetail>
  | ReturnType<typeof queryKeys.public.fieldNotes>
  | ReturnType<typeof queryKeys.public.volume>
  | ReturnType<typeof queryKeys.public.stats>
  | typeof queryKeys.assessments.all
  | ReturnType<typeof queryKeys.assessments.byChain>
  | ReturnType<typeof queryKeys.assessments.byGarden>
  | typeof queryKeys.conviction.all
  | ReturnType<typeof queryKeys.conviction.strategies>
  | ReturnType<typeof queryKeys.conviction.registeredHypercerts>
  | ReturnType<typeof queryKeys.conviction.convictionWeights>
  | ReturnType<typeof queryKeys.conviction.memberPower>
  | typeof queryKeys.community.all
  | ReturnType<typeof queryKeys.community.garden>
  | ReturnType<typeof queryKeys.community.pools>
  | typeof queryKeys.cookieJar.all
  | ReturnType<typeof queryKeys.cookieJar.byGarden>
  | ReturnType<typeof queryKeys.cookieJar.jarDetail>
  | ReturnType<typeof queryKeys.cookieJar.campaign>
  | ReturnType<typeof queryKeys.cookieJar.userHistory>
  | typeof queryKeys.yield.all
  | ReturnType<typeof queryKeys.yield.allocationsBase>
  | ReturnType<typeof queryKeys.yield.allocations>
  | ReturnType<typeof queryKeys.yield.byAsset>
  | ReturnType<typeof queryKeys.yield.splitConfig>
  | ReturnType<typeof queryKeys.yield.wiring>
  | ReturnType<typeof queryKeys.yield.pendingYield>
  | ReturnType<typeof queryKeys.yield.protocolSummary>
  | typeof queryKeys.ens.all
  | ReturnType<typeof queryKeys.ens.name>
  | ReturnType<typeof queryKeys.ens.address>
  | ReturnType<typeof queryKeys.ens.avatar>
  | ReturnType<typeof queryKeys.ens.registrationStatus>
  | ReturnType<typeof queryKeys.ens.availability>
  | ReturnType<typeof queryKeys.ens.protocolMembership>
  | typeof queryKeys.marketplace.all
  | ReturnType<typeof queryKeys.marketplace.orders>
  | ReturnType<typeof queryKeys.marketplace.activeOrder>
  | ReturnType<typeof queryKeys.marketplace.sellerOrders>
  | ReturnType<typeof queryKeys.marketplace.preview>
  | ReturnType<typeof queryKeys.marketplace.tradeHistory>
  | ReturnType<typeof queryKeys.marketplace.approvals>
  | ReturnType<typeof queryKeys.role.allowlist>;

export type WorksQueryKey =
  | typeof queryKeys.works.all
  | ReturnType<typeof queryKeys.works.online>
  | ReturnType<typeof queryKeys.works.offline>
  | ReturnType<typeof queryKeys.works.merged>
  | ReturnType<typeof queryKeys.works.approvals>;

export type QueueQueryKey =
  | typeof queryKeys.queue.all
  | ReturnType<typeof queryKeys.queue.stats>
  | ReturnType<typeof queryKeys.queue.jobs>
  | ReturnType<typeof queryKeys.queue.pendingCount>;
