/**
 * Read the aggregate project-supporting value generated by an Octant Yield
 * Donating Strategy pilot vault.
 *
 * Source of truth for v1: the deployed strategy's configured `dragonRouter()`
 * address, that router's vault-share balance, and `convertToAssets(shares)` for
 * a WETH-denominated estimate. If any source cannot be proven by read-only calls,
 * the hook returns an unavailable state rather than inventing a number.
 *
 * @module hooks/vault/useOctantVaultProjectSupportMetric
 */

import { useQuery } from "@tanstack/react-query";
import { createPublicClientForChain } from "../../config/pimlico";
import { queryKeys } from "../../config/query-keys";
import { STALE_TIME_MEDIUM } from "../../config/query-keys/constants";
import type { Address } from "../../types/domain";
import { OCTANT_VAULT_ABI } from "../../utils/blockchain/abis";
import { ZERO_ADDRESS } from "../../utils/blockchain/vaults";

export type OctantVaultProjectSupportMetricStatus = "unavailable" | "zero" | "positive";
export type OctantVaultProjectSupportMetricUnavailableReason =
  | "missing_vault"
  | "missing_source"
  | "read_error";

export interface OctantVaultProjectSupportMetric {
  status: OctantVaultProjectSupportMetricStatus;
  /** The configured donation/router/project-support address read from `dragonRouter()`. */
  sourceAddress: Address | null;
  /** Donation/project-supporting vault shares held by `sourceAddress`. */
  shareBalance: bigint;
  /** Estimated WETH value of `shareBalance`, from `convertToAssets(shareBalance)`. */
  assetValue: bigint;
  isLoading: boolean;
  isError: boolean;
  unavailableReason?: OctantVaultProjectSupportMetricUnavailableReason;
}

export interface UseOctantVaultProjectSupportMetricOptions {
  vaultAddress?: Address;
  chainId?: number;
  enabled?: boolean;
}

function isUsableAddress(value: unknown): value is Address {
  return (
    typeof value === "string" &&
    /^0x[a-fA-F0-9]{40}$/.test(value) &&
    value.toLowerCase() !== ZERO_ADDRESS.toLowerCase()
  );
}

export function useOctantVaultProjectSupportMetric(
  options: UseOctantVaultProjectSupportMetricOptions = {}
): OctantVaultProjectSupportMetric {
  const { vaultAddress, chainId } = options;
  const enabled = (options.enabled ?? true) && Boolean(vaultAddress && chainId);

  const query = useQuery({
    queryKey:
      vaultAddress && chainId
        ? queryKeys.vaults.projectSupportMetric(vaultAddress, chainId)
        : (["greengoods", "vaults", "projectSupportMetric", "disabled"] as const),
    enabled,
    staleTime: STALE_TIME_MEDIUM,
    queryFn: async () => {
      if (!vaultAddress || !chainId) {
        return {
          sourceAddress: null,
          shareBalance: 0n,
          assetValue: 0n,
          unavailableReason: "missing_vault" as const,
        };
      }

      const publicClient = createPublicClientForChain(chainId);
      const sourceAddressResult = await publicClient.readContract({
        address: vaultAddress,
        abi: OCTANT_VAULT_ABI,
        functionName: "dragonRouter",
      });

      if (!isUsableAddress(sourceAddressResult)) {
        return {
          sourceAddress: null,
          shareBalance: 0n,
          assetValue: 0n,
          unavailableReason: "missing_source" as const,
        };
      }

      const shareBalanceResult = await publicClient.readContract({
        address: vaultAddress,
        abi: OCTANT_VAULT_ABI,
        functionName: "balanceOf",
        args: [sourceAddressResult],
      });
      const shareBalance = typeof shareBalanceResult === "bigint" ? shareBalanceResult : 0n;

      let assetValue = 0n;
      let unavailableReason: OctantVaultProjectSupportMetricUnavailableReason | undefined;
      if (shareBalance > 0n) {
        try {
          const assetValueResult = await publicClient.readContract({
            address: vaultAddress,
            abi: OCTANT_VAULT_ABI,
            functionName: "convertToAssets",
            args: [shareBalance],
          });
          assetValue = typeof assetValueResult === "bigint" ? assetValueResult : 0n;
        } catch {
          unavailableReason = "read_error";
        }
      }

      return {
        sourceAddress: sourceAddressResult,
        shareBalance,
        assetValue,
        unavailableReason,
      };
    },
  });

  if (!enabled) {
    return {
      status: "unavailable",
      sourceAddress: null,
      shareBalance: 0n,
      assetValue: 0n,
      isLoading: false,
      isError: false,
      unavailableReason: "missing_vault",
    };
  }

  if (query.isError) {
    return {
      status: "unavailable",
      sourceAddress: null,
      shareBalance: 0n,
      assetValue: 0n,
      isLoading: false,
      isError: true,
      unavailableReason: "read_error",
    };
  }

  const data = query.data;
  if (data?.unavailableReason) {
    return {
      status: "unavailable",
      sourceAddress: data.sourceAddress,
      shareBalance: data.shareBalance,
      assetValue: data.assetValue,
      isLoading: query.isLoading,
      isError: false,
      unavailableReason: data.unavailableReason,
    };
  }

  const shareBalance = data?.shareBalance ?? 0n;
  const assetValue = data?.assetValue ?? 0n;
  return {
    status: assetValue > 0n ? "positive" : "zero",
    sourceAddress: data?.sourceAddress ?? null,
    shareBalance,
    assetValue,
    isLoading: query.isLoading,
    isError: false,
  };
}
