/**
 * The demo's commitments, written around the reader so the same world puts
 * them in every seat the screens draw: browsing, providing, helping,
 * confirming, asked and declined, kept, lapsed, disputed.
 *
 * @module modules/commitment-pooling/demo/demo-commitments
 */

import type { Address } from "../../../types/domain";
import type { CommitmentReadModel } from "../types-core";
import {
  commitment,
  DEMO_CAMPAIGN_ID,
  DEMO_GARDEN,
  DEMO_PROTOCOL_POOL_ID,
  EDU,
  MARIA,
  ROSA,
  TUNDE,
} from "./demo-builders";

export function demoCommitments(V: Address): CommitmentReadModel[] {
  return [
    // Browsing: a neighbour's open offer the reader may take up.
    commitment({
      commitmentId: 1001n,
      direction: "OFFER",
      commitmentType: "SUPPORT_SERVICE",
      onchainState: "OFFERED",
      creator: ROSA,
      leadProvider: ROSA,
      unitLabel: "rides",
      targetUnits: 3n,
    }),
    // The reader's own open offer of garden work: withdrawable.
    commitment({
      commitmentId: 1002n,
      direction: "OFFER",
      commitmentType: "DOMAIN_IMPACT",
      onchainState: "OFFERED",
      creator: V,
      leadProvider: V,
      targetUnits: 4n,
    }),
    // A steward-reviewed request the reader may ask to take up.
    commitment({
      commitmentId: 1003n,
      direction: "REQUEST",
      commitmentType: "SUPPORT_SERVICE",
      onchainState: "REQUESTED",
      creator: TUNDE,
      claimMode: "APPROVAL_GATED",
      unitLabel: "sessions",
      targetUnits: 2n,
      cycleId: DEMO_CAMPAIGN_ID,
    }),
    // The reader already asked: pending.
    commitment({
      commitmentId: 1004n,
      direction: "REQUEST",
      commitmentType: "SUPPORT_SERVICE",
      onchainState: "REQUESTED",
      creator: MARIA,
      claimMode: "APPROVAL_GATED",
      unitLabel: "meals",
      targetUnits: 6n,
    }),
    // The reader asked and was declined, with the steward's reason.
    commitment({
      commitmentId: 1005n,
      direction: "REQUEST",
      commitmentType: "SUPPORT_SERVICE",
      onchainState: "REQUESTED",
      creator: EDU,
      claimMode: "APPROVAL_GATED",
      unitLabel: "repairs",
      targetUnits: 1n,
    }),
    // Somebody else took it up first: the reader's request is superseded.
    commitment({
      commitmentId: 1006n,
      direction: "OFFER",
      commitmentType: "SUPPORT_SERVICE",
      onchainState: "ACCEPTED",
      derivedState: "ACTIVE",
      creator: ROSA,
      leadProvider: ROSA,
      counterparty: TUNDE,
      claimMode: "APPROVAL_GATED",
      unitLabel: "rides",
      targetUnits: 2n,
    }),
    // The reader leads garden work with an open team: add proof, link work.
    commitment({
      commitmentId: 1007n,
      direction: "OFFER",
      commitmentType: "DOMAIN_IMPACT",
      onchainState: "ACCEPTED",
      derivedState: "PARTIALLY_APPROVED",
      creator: V,
      leadProvider: V,
      counterparty: ROSA,
      contributorPolicy: "OPEN",
      contributorCount: 2,
      approvedUnits: 1n,
      evidenceCount: 1,
      targetUnits: 6n,
    }),
    // The reader's support offer with proof attached: ready to send.
    commitment({
      commitmentId: 1008n,
      direction: "OFFER",
      commitmentType: "SUPPORT_SERVICE",
      onchainState: "ACCEPTED",
      derivedState: "EVIDENCE_SUBMITTED",
      creator: V,
      leadProvider: V,
      counterparty: MARIA,
      evidenceCount: 2,
      unitLabel: "sessions",
      targetUnits: 2n,
      cycleId: DEMO_CAMPAIGN_ID,
    }),
    // The reader took up a neighbour's support offer: their confirmation.
    commitment({
      commitmentId: 1009n,
      direction: "OFFER",
      commitmentType: "SUPPORT_SERVICE",
      onchainState: "READY_FOR_CONFIRMATION",
      creator: MARIA,
      leadProvider: MARIA,
      counterparty: V,
      evidenceCount: 2,
      unitLabel: "rides",
      targetUnits: 3n,
    }),
    // The reader asked for garden work; it was done: confirm the work.
    commitment({
      commitmentId: 1010n,
      direction: "REQUEST",
      commitmentType: "DOMAIN_IMPACT",
      onchainState: "READY_FOR_CONFIRMATION",
      creator: V,
      leadProvider: TUNDE,
      counterparty: TUNDE,
      approvedUnits: 4n,
      evidenceCount: 3,
      targetUnits: 4n,
    }),
    // Kept, confirmed the ordinary way.
    commitment({
      commitmentId: 1011n,
      direction: "OFFER",
      commitmentType: "SUPPORT_SERVICE",
      onchainState: "FULFILLED",
      creator: V,
      leadProvider: V,
      counterparty: ROSA,
      evidenceCount: 1,
      confirmationCount: 1,
      fulfilledBy: ROSA,
      confirmationPath: "ORDINARY",
      unitLabel: "meals",
      targetUnits: 12n,
    }),
    // Kept by a steward stepping in, with the reason on record.
    commitment({
      commitmentId: 1012n,
      direction: "OFFER",
      commitmentType: "DOMAIN_IMPACT",
      onchainState: "FULFILLED",
      creator: V,
      leadProvider: V,
      counterparty: EDU,
      approvedUnits: 2n,
      evidenceCount: 2,
      confirmationCount: 1,
      fulfilledBy: ROSA,
      confirmationPath: "POOL_FALLBACK",
      fallbackReason: "The neighbour who took this up moved away before confirming.",
      targetUnits: 2n,
    }),
    // Lapsed: offer it again.
    commitment({
      commitmentId: 1013n,
      direction: "OFFER",
      commitmentType: "SUPPORT_SERVICE",
      onchainState: "EXPIRED",
      creator: V,
      leadProvider: V,
      unitLabel: "repairs",
      targetUnits: 1n,
    }),
    // Withdrawn.
    commitment({
      commitmentId: 1014n,
      direction: "REQUEST",
      commitmentType: "SUPPORT_SERVICE",
      onchainState: "CANCELLED",
      creator: V,
      unitLabel: "rides",
      targetUnits: 1n,
    }),
    // Under review after a Not yet.
    commitment({
      commitmentId: 1015n,
      direction: "OFFER",
      commitmentType: "SUPPORT_SERVICE",
      onchainState: "DISPUTED",
      creator: V,
      leadProvider: V,
      counterparty: TUNDE,
      evidenceCount: 1,
      unitLabel: "sessions",
      targetUnits: 1n,
    }),
    // A neighbour's open team the reader may join.
    commitment({
      commitmentId: 1016n,
      direction: "OFFER",
      commitmentType: "DOMAIN_IMPACT",
      onchainState: "ACCEPTED",
      derivedState: "ACTIVE",
      creator: ROSA,
      leadProvider: ROSA,
      counterparty: EDU,
      contributorPolicy: "OPEN",
      contributorCount: 2,
      targetUnits: 8n,
    }),
    // The reader is on somebody else's team: proof yes, send no.
    commitment({
      commitmentId: 1017n,
      direction: "OFFER",
      commitmentType: "DOMAIN_IMPACT",
      onchainState: "ACCEPTED",
      derivedState: "ACTIVE",
      creator: TUNDE,
      leadProvider: TUNDE,
      counterparty: MARIA,
      contributorPolicy: "OPEN",
      contributorsFrozen: true,
      contributorCount: 3,
      targetUnits: 5n,
    }),
    // Recorded by a steward for a neighbour; the reader confirms it.
    commitment({
      commitmentId: 1018n,
      direction: "OFFER",
      commitmentType: "SUPPORT_SERVICE",
      onchainState: "READY_FOR_CONFIRMATION",
      creator: EDU,
      leadProvider: EDU,
      counterparty: V,
      recordedBy: ROSA,
      evidenceCount: 1,
      unitLabel: "sessions",
      targetUnits: 1n,
    }),
    // A named group confirms, two of them, and one has already.
    commitment({
      commitmentId: 1019n,
      direction: "OFFER",
      commitmentType: "SUPPORT_SERVICE",
      onchainState: "READY_FOR_CONFIRMATION",
      creator: TUNDE,
      leadProvider: TUNDE,
      counterparty: EDU,
      confirmers: [V, MARIA],
      confirmationCount: 1,
      confirmationThreshold: 2,
      evidenceCount: 2,
      unitLabel: "repairs",
      targetUnits: 2n,
    }),
    // The garden took this up; its stewards confirm it (To confirm tab).
    commitment({
      commitmentId: 1020n,
      direction: "OFFER",
      commitmentType: "SUPPORT_SERVICE",
      onchainState: "READY_FOR_CONFIRMATION",
      creator: TUNDE,
      leadProvider: TUNDE,
      counterparty: DEMO_GARDEN,
      counterpartyKind: "GARDEN",
      evidenceCount: 1,
      unitLabel: "rides",
      targetUnits: 4n,
    }),
    // An open offer in the protocol pool: the provider context is a choice.
    commitment({
      commitmentId: 1021n,
      direction: "OFFER",
      commitmentType: "SUPPORT_SERVICE",
      onchainState: "OFFERED",
      poolId: DEMO_PROTOCOL_POOL_ID,
      cycleId: null,
      creator: MARIA,
      leadProvider: MARIA,
      unitLabel: "sessions",
      targetUnits: 3n,
    }),
  ];
}
