/**
 * Reown AppKit Configuration
 *
 * Provides wallet connection UI with Green Goods branding.
 * Used as fallback for operators/admins who prefer traditional wallet login.
 *
 * This is the SINGLE source of truth for Wagmi configuration.
 * The WagmiAdapter generates the wagmiConfig that should be used throughout the app.
 *
 * @module config/appkit
 * @see https://reown.com/appkit for documentation
 */

import { createAppKit } from "@reown/appkit/react";
import { WagmiAdapter } from "@reown/appkit-adapter-wagmi";
import { baseSepolia, celo, arbitrum, type Chain } from "viem/chains";

/**
 * WalletConnect Project ID from environment variables.
 * Required for AppKit to function.
 */
const projectId = import.meta.env.VITE_WALLETCONNECT_PROJECT_ID;

if (!projectId) {
  console.warn("[AppKit] VITE_WALLETCONNECT_PROJECT_ID not set. Wallet login will not work.");
}

/**
 * Application metadata for wallet connection UI
 */
const metadata = {
  name: "Green Goods",
  description: "Start Bringing Biodiversity Onchain",
  url: import.meta.env.VITE_APP_URL || window.location.origin,
  icons: ["https://greengoods.app/icon.png"],
};

/**
 * Supported networks for wallet connections.
 * Includes testnets and production networks.
 */
export const networks: [Chain, ...Chain[]] = [baseSepolia, celo, arbitrum] as [Chain, ...Chain[]];

/**
 * Initialize Wagmi Adapter for AppKit.
 * This adapter manages wallet connections and generates the Wagmi config.
 */
export const wagmiAdapter = new WagmiAdapter({
  networks,
  projectId: projectId || "",
});

/**
 * Wagmi configuration generated by the WagmiAdapter.
 * This is the config that should be used with WagmiProvider.
 *
 * IMPORTANT: Use this config instead of creating a separate Wagmi config.
 * AppKit and the rest of the app must share the same Wagmi instance.
 */
export const wagmiConfig = wagmiAdapter.wagmiConfig;

/**
 * Initialize AppKit with Green Goods branding and configuration.
 *
 * Features:
 * - Supports MetaMask, WalletConnect, Coinbase Wallet, and 500+ wallets
 * - Custom Green Goods theming
 * - Mobile-optimized bottom sheet UI
 * - Telegram mini-app support (via WalletConnect)
 *
 * Singleton pattern: Only initialize once to avoid double initialization warnings.
 *
 * @see https://reown.com/appkit/react/core/installation
 */
let appKitInstance: ReturnType<typeof createAppKit> | null = null;

export const appKit =
  appKitInstance ||
  (appKitInstance = createAppKit({
    adapters: [wagmiAdapter],
    networks,
    projectId: projectId || "",
    metadata,
    features: {
      analytics: false, // Disable AppKit analytics (we use PostHog)
    },
    themeMode: "light",
    themeVariables: {
      "--w3m-accent": "#367D42", // Green Goods primary green
      "--w3m-border-radius-master": "12px",
    },
  }));
