import {
  formatAddress,
  resolveAvatarUrl,
  useAuth,
  useENSRegistrationStatus,
  useEnsAvatar,
  useEnsName,
  useGardenerProfile,
  useProtocolMemberStatus,
  useUser,
} from "@green-goods/shared";
import { RiGlobalLine, RiHeadphoneLine, RiSettings2Fill } from "@remixicon/react";
import { useState } from "react";
import { useIntl } from "react-intl";
import { Profile as UserProfile } from "@/components/Features";
import { type StandardTab, StandardTabs } from "@/components/Navigation";
import { ProfileAccount } from "./Account";
import { ProfileHelp } from "./Help";

const DEFAULT_AVATAR = "/images/avatar.png";

/** Check if username is auto-generated (e.g., user_1234567890) */
const isAutoGeneratedUsername = (name: string | null | undefined): boolean => {
  if (!name) return true;
  return /^user_\d+$/.test(name);
};

const Profile: React.FC = () => {
  const { user } = useUser();
  const { userName } = useAuth();
  const { profile } = useGardenerProfile();
  const intl = useIntl();
  const [activeTab, setActiveTab] = useState<"account" | "help">("account");

  const primaryAddress = user?.id;

  // ENS resolution - called directly here since we're inside QueryClientProvider
  const { data: ensName } = useEnsName(primaryAddress);
  const { data: ensAvatar, isLoading: isLoadingAvatar } = useEnsAvatar(primaryAddress ?? undefined);

  const formattedAddress = primaryAddress ? formatAddress(primaryAddress, { ensName }) : null;

  const fallbackDisplayName = intl.formatMessage({
    id: "app.garden.gardeners.unknownUser",
    defaultMessage: "Unknown User",
  });

  // Get user-set username (only if not auto-generated)
  const userSetName = isAutoGeneratedUsername(userName) ? null : userName;

  // Display name priority: profile name > ENS > user-set passkey name > formatted address > fallback
  const displayName =
    profile?.name?.trim() || ensName || userSetName || formattedAddress || fallbackDisplayName;

  const headerAvatar = profile?.imageURI
    ? resolveAvatarUrl(profile.imageURI)
    : ensAvatar || DEFAULT_AVATAR;

  // ENS eligibility badge
  const { data: isProtocolMember = false } = useProtocolMemberStatus(
    primaryAddress as `0x${string}` | undefined
  );
  const { data: ensRegistration } = useENSRegistrationStatus(undefined);
  const showENSBadge =
    isProtocolMember && (!ensRegistration || ensRegistration.status === "available");

  const tabs: StandardTab[] = [
    {
      id: "account",
      label: intl.formatMessage({
        id: "app.profile.account",
        description: "Account",
      }),
      icon: <RiSettings2Fill className="w-4" />,
    },
    {
      id: "help",
      label: intl.formatMessage({
        id: "app.profile.help",
        description: "Help",
      }),
      icon: <RiHeadphoneLine className="w-4" />,
    },
  ];

  return (
    <section className="flex h-full flex-col">
      {/* Fixed Header */}
      <div className="fixed left-0 top-0 z-10 w-full bg-bg-white-0">
        <div className="px-4 pt-6 pb-4">
          <UserProfile
            displayName={displayName}
            avatar={headerAvatar}
            isLoadingAvatar={isLoadingAvatar && !profile?.imageURI}
            location={profile?.location?.trim() || undefined}
          />
        </div>

        {/* ENS claim discovery badge */}
        {showENSBadge && (
          <button
            type="button"
            onClick={() => setActiveTab("account")}
            className="mx-4 mb-2 flex items-center gap-2 rounded-full bg-green-50 px-3 py-1.5 text-xs font-medium text-green-700 transition-colors hover:bg-green-100 active:scale-[0.98]"
          >
            <RiGlobalLine className="h-3.5 w-3.5" />
            {intl.formatMessage({
              id: "app.profile.claimENSBadge",
              defaultMessage: "Claim your .greengoods.eth name",
            })}
          </button>
        )}

        {/* Full Screen Tabs - outside padding */}
        <StandardTabs
          tabs={tabs}
          activeTab={activeTab}
          onTabChange={(tabId) => setActiveTab(tabId as "account" | "help")}
          variant="compact"
          scrollTargetSelector="#profile-scroll"
        />
      </div>

      {/* Content - pb-24 ensures last items (logout) are visible above viewport edge */}
      <div
        id="profile-scroll"
        className="flex-1 overflow-x-hidden overflow-y-auto pt-64 pb-24 native-scroll"
      >
        <div className="padded my-4 flex flex-col gap-4">
          {activeTab === "help" ? <ProfileHelp /> : <ProfileAccount />}
        </div>
      </div>
    </section>
  );
};

export default Profile;
