import {
  formatEnsNameForDisplay,
  resolveAvatarUrl,
  useAuthState,
  useEnsAvatar,
  useEnsName,
  useGardenerProfile,
  useUser,
} from "@green-goods/shared";
import { RiAwardLine, RiHeadphoneLine, RiSettings2Fill } from "@remixicon/react";
import { useState } from "react";
import { useIntl } from "react-intl";
import { useSearchParams } from "react-router-dom";
import { Profile as UserProfile } from "@/components/Features";
import { type StandardTab, StandardTabs } from "@/components/Navigation";
import { ProfileAccount } from "./Account";
import { ProfileBadges } from "./Badges";
import { ProfileHelp } from "./Help";

const DEFAULT_AVATAR = "/images/avatar.png";

/** Check if username is auto-generated (e.g., user_1234567890) */
const isAutoGeneratedUsername = (name: string | null | undefined): boolean => {
  if (!name) return true;
  return /^user_\d+$/.test(name);
};

const Profile: React.FC = () => {
  const { user } = useUser();
  const { userName } = useAuthState();
  const { profile } = useGardenerProfile();
  const intl = useIntl();

  // Allow deep-linking a tab via ?tab= (e.g. the arrival toast's "Open Help" → ?tab=help).
  const [searchParams] = useSearchParams();
  const requestedTab = searchParams.get("tab");
  const initialTab: "account" | "badges" | "help" =
    requestedTab === "help" || requestedTab === "badges" ? requestedTab : "account";
  const [activeTab, setActiveTab] = useState<"account" | "badges" | "help">(initialTab);

  const primaryAddress = user?.id;

  // ENS resolution - called directly here since we're inside QueryClientProvider
  const { data: ensName } = useEnsName(primaryAddress);
  const { data: ensAvatar, isLoading: isLoadingAvatar } = useEnsAvatar(primaryAddress ?? undefined);
  const displayEnsName = formatEnsNameForDisplay(ensName);

  const fallbackDisplayName = intl.formatMessage({
    id: "app.profile.displayNameFallback",
    defaultMessage: "Your profile",
  });

  // Skip auto-generated passkey usernames so we don't display them as user-set names.
  const userSetName = isAutoGeneratedUsername(userName) ? null : userName;

  // Display name priority: profile name > ENS > user-set passkey name > friendly fallback.
  // Raw addresses are intentionally not part of the gardener-default identity surface;
  // they live behind the "Account details" disclosure on the Account tab.
  const displayName = profile?.name?.trim() || displayEnsName || userSetName || fallbackDisplayName;

  const headerAvatar = profile?.imageURI
    ? resolveAvatarUrl(profile.imageURI)
    : ensAvatar || DEFAULT_AVATAR;

  const tabs: StandardTab[] = [
    {
      id: "account",
      label: intl.formatMessage({
        id: "app.profile.account",
        description: "Account",
      }),
      icon: <RiSettings2Fill className="w-4" />,
    },
    {
      id: "badges",
      label: intl.formatMessage({
        id: "app.profile.badges",
        description: "Badges",
      }),
      icon: <RiAwardLine className="w-4" />,
    },
    {
      id: "help",
      label: intl.formatMessage({
        id: "app.profile.help",
        description: "Help",
      }),
      icon: <RiHeadphoneLine className="w-4" />,
    },
  ];

  return (
    <section className="flex h-full flex-col">
      {/* Fixed Header */}
      <div className="fixed left-0 top-0 z-10 w-full bg-bg-white-0">
        <div className="px-4 pt-6 pb-4">
          <UserProfile
            displayName={displayName}
            avatar={headerAvatar}
            isLoadingAvatar={isLoadingAvatar && !profile?.imageURI}
            location={profile?.location?.trim() || undefined}
          />
        </div>

        {/* Full Screen Tabs - outside padding */}
        <StandardTabs
          tabs={tabs}
          activeTab={activeTab}
          onTabChange={(tabId) => setActiveTab(tabId as "account" | "badges" | "help")}
          variant="compact"
          scrollTargetSelector="#profile-scroll"
        />
      </div>

      {/* Content - pb-24 ensures last items (logout) are visible above viewport edge */}
      <div
        id="profile-scroll"
        className="flex-1 overflow-x-hidden overflow-y-auto pt-64 pb-24 native-scroll"
      >
        <div className="padded my-4 flex flex-col gap-4">
          {activeTab === "help" ? (
            <ProfileHelp />
          ) : activeTab === "badges" ? (
            <ProfileBadges />
          ) : (
            <ProfileAccount />
          )}
        </div>
      </div>
    </section>
  );
};

export default Profile;
