import { writeFileSync } from "node:fs";
import path from "node:path";

// Exclusive creation protects an environment written by another session during setup.
export function createBaselineEnv(root, profile) {
  const content = [
    "# Non-secret Green Goods baseline generated by setup profile.",
    "# Replace or extend this file locally when a workflow needs credentials.",
    `GG_WORKSPACE_PROFILE=${profile}`,
    "APP_ENV=development",
    "VITE_CHAIN_ID=11155111",
    "VITE_API_BASE_URL=http://127.0.0.1:3005",
    "VITE_ENVIO_INDEXER_URL=http://localhost:3006/v1/graphql",
    "",
  ].join("\n");
  try {
    writeFileSync(path.join(root, ".env"), content, { mode: 0o600, flag: "wx" });
    return true;
  } catch (error) {
    if (error.code === "EEXIST") return false;
    throw error;
  }
}
