// Main entry point for @green-goods/shared
// EXPLICIT EXPORTS for tree-shaking - organized by category

// ============================================================================
// COMPONENTS
// ============================================================================
export type {
  AudioPlayerProps,
  AudioRecorderProps,
  ConfidenceSelectorProps,
  ConfirmDialogProps,
  DatePickerProps,
  DateRangePickerProps,
  ErrorBoundaryProps,
  FormatMessageFn,
  FormInputProps,
  FormLayoutProps,
  FormSelectOption,
  FormSelectProps,
  FormTextareaProps,
  HydrationFallbackProps,
  ImageWithFallbackProps,
  MethodSelectorProps,
  SpinnerProps,
  StatusBadgeProps,
  ToastAction,
  ToastDescriptor,
  ToastHandle,
  ToastStatus,
  ToastTranslator,
  ToastViewportProps,
  WorkCardData,
  WorkStatus,
  BadgeProps,
  BadgeVariantProps,
} from "./components/index";
export {
  AssetSelector,
  Badge,
  badgeVariants,
  AudioPlayer,
  AudioRecorder,
  ConfidenceSelector,
  ConfirmDialog,
  DatePicker,
  DateRangePicker,
  ENSProgressTimeline,
  ErrorBoundary,
  FormInput,
  FormLayout,
  FormTextarea,
  getStatusColors,
  HydrationFallback,
  ImageWithFallback,
  MethodSelector,
  SyncStatusBar,
  Spinner,
  StatusBadge,
  ToastViewport,
  TranslationBadge,
  FormSelect,
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectScrollDownButton,
  SelectScrollUpButton,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
  toastService,
  updateToasts,
  WorkCard as WorkCardComponent,
} from "./components/index";

// ============================================================================
// CONFIG
// ============================================================================
export {
  APP_DEFAULT_TITLE,
  APP_DESCRIPTION,
  APP_ICON,
  APP_NAME,
  APP_TITLE_TEMPLATE,
  APP_URL,
  createPublicClientForChain,
  DEFAULT_CHAIN_ID,
  getChain,
  getChainName,
  getDefaultChain,
  getEASConfig,
  getIndexerUrl,
  getNetworkConfig,
  isChainSupported,
  isPasskeyAvailable,
  ONBOARDED_STORAGE_KEY,
  queryClient,
  SDG_TARGETS,
  getSDGLabel,
  SUPPORTED_CHAINS,
  type SupportedChainId,
} from "./config/index";

// ============================================================================
// HOOKS
// ============================================================================
export type {
  CarouselContextProps,
  CarouselProps,
  // Assessment hook types
  AssessmentDraftRecord,
  UseAssessmentDraftResult,
  AssessmentFormData,
  UseAssessmentFormReturn,
  CreateActionFormData,
  CreateAssessmentForm,
  CreateAssessmentFormData,
  AssessmentStepId,
  UseCreateAssessmentFormReturn,
  // Garden hook types
  CreateGardenFormData,
  GardenStepId,
  UseCreateGardenFormReturn,
  GardenDraft,
  UseGardenDraftResult,
  DebugModeState,
  DeploymentAllowlistResult,
  DeploymentRegistryPermissions,
  DraftWithImages,
  EnhancedWorkApproval,
  GardenerProfile,
  GardenInvite,
  GardenOperationConfig,
  GardenPermissions,
  InstallAction,
  InstallGuidance,
  InstallScenario,
  ManualInstallStep,
  QueryKey,
  QueueQueryKey,
  RoleInfo,
  ServiceWorkerUpdateState,
  ToastActionOptions,
  UseAttestationsResult,
  UseDraftsReturn,
  UseHypercertDraftResult,
  UseHypercertsResult,
  UseMintHypercertResult,
  // Marketplace hook types
  UseHypercertListingsResult,
  UseMarketplaceApprovalsResult,
  UseTradeHistoryResult,
  UseCreateListingResult,
  ListingStep,
  UseCancelListingResult,
  UseBatchListForYieldResult,
  BatchProgress,
  UseAnalyticsIdentityOptions,
  UsePageViewOptions,
  UseCopyToClipboardOptions,
  UseCopyToClipboardReturn,
  UseAudioRecordingOptions,
  UseAudioRecordingReturn,
  UseDepositFormResult,
  UserRole,
  ActionFiltersState,
  ActionSortOrder,
  UseFilteredActionsResult,
  GardenFilterScope,
  GardenFiltersState,
  GardenSortOrder,
  GardenOperationResult,
  WorkFormData,
  WorksQueryKey,
  ENSClaimResult,
  SlugFormValues,
} from "./hooks/index";
export {
  checkMembership,
  ensureBaseLists,
  GardenTab,
  queryInvalidation,
  queryKeys,
  // Query constants
  DEFAULT_RETRY_COUNT,
  STALE_TIME_FAST,
  STALE_TIME_MEDIUM,
  STALE_TIME_SLOW,
  // Utility hooks (documented API patterns — keep even with low external usage)
  useAsyncEffect,
  useAsyncSetup,
  useDelayedInvalidation,
  useEventListener,
  useTimeout,
  useWindowEvent,
  useDocumentEvent,
  // Action hooks
  createActionSchema,
  useActionOperations,
  useActions,
  useActionTranslation,
  useAnalyticsIdentity,
  useAuth,
  useAutoJoinRootGarden,
  useBrowserNavigation,
  useCopyToClipboard,
  useDebouncedValue,
  useDepositForm,
  useAddressInput,
  useMutationLock,
  useBeforeUnloadWhilePending,
  useAudioRecording,
  // Cookie jar hooks
  useGardenCookieJars,
  useCookieJarWithdraw,
  useCookieJarDeposit,
  useCookieJarPause,
  useCookieJarUnpause,
  useCookieJarEmergencyWithdraw,
  useCookieJarUpdateMaxWithdrawal,
  useCookieJarUpdateInterval,
  useUserCookieJars,
  useConvictionStrategies,
  useSetConvictionStrategies,
  useRegisteredHypercerts,
  useHypercertConviction,
  useMemberVotingPower,
  useAllocateHypercertSupport,
  useRegisterHypercert,
  useDeregisterHypercert,
  useSetDecay,
  useSetPointsPerVoter,
  useSetRoleHatIds,
  useGardenCommunity,
  useGardenPools,
  useCreateGardenPools,
  useAllocateYield,
  useYieldAllocations,
  // Assessment hooks
  useAssessmentDraft,
  assessmentFormSchema,
  useAssessmentForm,
  createDefaultAssessmentFormData,
  assessmentStepFields,
  createAssessmentFormSchema,
  createDefaultAssessmentForm,
  useCreateAssessmentForm,
  useCreateAssessmentWorkflow,
  useCreateHypercertWorkflow,
  // Garden hooks
  createGardenSchema,
  gardenStepFields,
  useCreateGardenForm,
  createDefaultGardenForm,
  useGardenDraft,
  useCreateGardenWorkflow,
  useCurrentChain,
  useDebugMode,
  DEPLOYMENT_REGISTRY_ABI,
  useDeploymentAllowlist,
  useDeploymentRegistry,
  useEnsAddress,
  useEnsAvatar,
  useEnsName,
  // ENS registration hooks
  useENSClaim,
  useENSRegistrationStatus,
  useProtocolMemberStatus,
  slugSchema,
  useSlugForm,
  useSlugAvailability,
  useGardenAssessments,
  useGardenDomains,
  useSetGardenDomains,
  useGardenerProfile,
  useGardeners,
  useGardenInvites,
  useGardenOperations,
  useGardenPermissions,
  useGardenVaults,
  useGardens,
  useGardenTabs,
  useGardenTranslation,
  useHasRole,
  // Hypercert hooks (grouped together, prefixed with useHypercert*)
  useHypercertAttestations,
  useHypercertAllowlist,
  useHypercertContributorWeights,
  useHypercertDraft,
  useHypercerts,
  type OptimisticHypercertData,
  useMintHypercert,
  // Marketplace hooks
  useHypercertListings,
  useMarketplaceApprovals,
  useTradeHistory,
  useCreateListing,
  useCancelListing,
  useBatchListForYield,
  useInstallGuidance,
  isGardenMember,
  useJoinGarden,
  useMyOnlineWorks,
  useMyWorks,
  useNavigateToTop,
  useNetworkConfig,
  useOffline,
  usePageView,
  usePendingWorksCount,
  useRole,
  useServiceWorkerUpdate,
  useTheme,
  useTranslation,
  useUser,
  useVaultDeposit,
  useVaultDeposits,
  useVaultEvents,
  useVaultPreview,
  useVaultWithdraw,
  useHarvest,
  useEmergencyPause,
  useConfigureVaultRoles,
  useBatchWorkSync,
  CarouselContext,
  useCarousel,
  useDraftAutoSave,
  useDraftResume,
  useDrafts,
  useFilteredActions,
  useFilteredGardens,
  useLoadingWithMinDuration,
  usePrimaryAddress,
  useWorkApproval,
  useWorkApprovals,
  useWorkForm,
  useWorkImages,
  useWorkMutation,
  useWorks,
  getOpsRunnerBaseUrl,
  useOpsRunnerSession,
  useOpsRunnerHealth,
  useOpsRunnerAuth,
  useOpsRunnerScripts,
  useOpsRunnerJobs,
  useOpsRunnerJob,
  useOpsDeployPlan,
  useOpsFinalizeDeploy,
  useOpsUpgradePlan,
  useOpsFinalizeUpgrade,
  useOpsRunScript,
  useOpsJobLogs,
} from "./hooks/index";
// ============================================================================
// I18N
// ============================================================================
export { en, es, pt } from "./i18n/index";
// ============================================================================
// MODULES
// ============================================================================
export type {
  FragmentOf,
  PasskeyApprovalSubmissionParams,
  PasskeyWorkSubmissionParams,
  ResultOf,
  VariablesOf,
  // Error tracking types
  ErrorSeverity,
  ErrorCategory,
  ErrorContext,
  BreadcrumbEntry,
  // Logger types
  LogContext,
  Logger,
} from "./modules/index";
export {
  // Session management
  AUTH_MODE_STORAGE_KEY,
  browserTranslator,
  clearAllAuth,
  clearStoredPasskey,
  filterAttestationsByAssessment,
  type AssessmentMetadataPrefill,
  prefillMetadataFromAssessment,
  getApprovedAttestations,
  getAuthMode,
  getFileByHash,
  hasStoredPasskey,
  initializeIpfsFromEnv,
  jobQueue,
  resolveAvatarUrl,
  resolveIPFSUrl,
  serviceWorkerManager,
  submitApprovalBot,
  submitWorkBot,
  track,
  trackAppLifecycle,
  trackOfflineEvent,
  // Admin deploy tracking
  trackAdminDeployStarted,
  trackAdminDeploySuccess,
  trackAdminDeployFailed,
  // Error tracking
  trackError,
  trackAuthError,
  trackSyncError,
  trackErrorBoundary,
  initGlobalErrorHandlers,
  // Logging
  logger,
  updateUserProfile,
  uploadFileToIPFS,
  uploadJSONToIPFS,
  useJobQueueEvents,
  jobQueueEventBus,
  // Data fetching functions
  getGardens,
  getWorks,
  getWorkApprovals,
  // Media resource manager (public API)
  mediaResourceManager,
} from "./modules/index";
// ============================================================================
// HYPERCERTS LIB
// ============================================================================
export {
  TOTAL_UNITS,
  TransferRestrictions,
  buildContributorStats,
  buildContributorWeights,
  calculateDistribution,
  formatHypercertMetadata,
  hypercertMetadataSchema,
  sumUnits,
} from "./lib/hypercerts";
export type { ContributorWeight, DistributionMode } from "./lib/hypercerts";
// ============================================================================
// PROVIDERS (re-export via subpath import recommended: @green-goods/shared/providers)
// ============================================================================
export type { Locale } from "./providers/index";
export {
  AppKitProvider,
  AppProvider,
  // Unified auth provider (supports both passkey and wallet)
  AuthProvider,
  // Job Queue & Work
  JobQueueProvider,
  useApp,
  useAppKit,
  useJobQueue,
  useQueueFlush,
  useWork,
  useWorkFormContext,
  useWorkSelection,
  WorkProvider,
} from "./providers/index";
// ============================================================================
// STORES (re-export via subpath import recommended: @green-goods/shared/stores)
// ============================================================================
export {
  type AdminState,
  type CreateAssessmentFormState,
  type CreateAssessmentStore,
  type CreateGardenFormState,
  type HypercertWizardStore,
  type MintingState,
  resetCreateAssessmentStore,
  resetCreateGardenStore,
  useAdminStore,
  useCreateAssessmentStore,
  useCreateGardenStore,
  useHypercertWizardStore,
  useUIStore,
  useWorkFlowStore,
  WorkTab,
} from "./stores/index";
// ============================================================================
// TYPES
// ============================================================================
export type {
  // Domain types
  Address,
  ENSRegistrationData,
  GardenerCard,
  GardenCard,
  Garden,
  GardenAssessment,
  AssessmentAttachment,
  AssessmentDraft,
  SmartOutcome,
  ActionCard,
  Action,
  WorkInput,
  WorkDraft,
  WorkCard,
  Work,
  WorkMetadata,
  WorkMetadataV1,
  WorkSubmission,
  WorkApprovalDraft,
  WorkApproval,
  ActionInstructionConfig,
  Link,
  // Hypercert types
  ActionDomain,
  ActionType,
  AllowlistEntry,
  AttestationFilters,
  AttestationRef,
  CapitalType,
  CustomMetric,
  GreenGoodsExtension,
  HypercertAllowlistClaim,
  HypercertAttestation,
  HypercertDraft,
  HypercertMetadata,
  HypercertListing,
  HypercertRecord,
  HypercertStatus,
  ListingStatus,
  CreateListingParams,
  FractionTrade,
  RegisteredOrderView,
  MetricValue,
  OutcomeMetrics,
  PredefinedMetric,
  PropertyDefinition,
  ScopeDefinition,
  TimeframeDefinition,
  // Job queue types
  Job,
  QueueEvent,
  JobProcessor,
  WorkJobPayload,
  ApprovalJobPayload,
  JobKindMap,
  JobKind,
  JobPayload,
  QueueSubscriber,
  QueueStats,
  JobQueueDBImage,
  CachedWork,
  // Offline types
  OfflineStatus,
  OfflineDashboardData,
  OfflineWorkItem,
  SyncMetrics,
  OfflineSettings,
  OfflineCapabilities,
  WorkConflict,
  DuplicateCheckResult,
  // Indexer response types
  IndexerGarden,
  IndexerGardensResponse,
  IndexerAction,
  IndexerActionsResponse,
  IndexerGardener,
  IndexerGardenersResponse,
  GardenVault,
  VaultDeposit,
  VaultEvent,
  VaultEventType,
  VaultPreview,
  DepositParams,
  WithdrawParams,
  HarvestParams,
  EmergencyPauseParams,
  // Cookie jar types
  CookieJar,
  CookieJarAdminParams,
  CookieJarDepositParams,
  CookieJarEmergencyWithdrawParams,
  CookieJarUpdateIntervalParams,
  CookieJarUpdateMaxWithdrawalParams,
  CookieJarWithdrawParams,
  // EAS response types
  EASAttestationRaw,
  EASAttestationsResponse,
  EASDecodedField,
  EASGardenAssessment,
  EASWork,
  EASWorkApproval,
  // Conviction types
  SetConvictionStrategiesParams,
  HypercertSignal,
  HypercertEntry,
  ConvictionWeight,
  MemberPower,
  VoterAllocation,
  AllocateHypercertSupportParams,
  RegisterHypercertParams,
  DeregisterHypercertParams,
  SetDecayParams,
  SetPointsPerVoterParams,
  SetRoleHatIdsParams,
  // Gardens community types
  WeightSchemeConfig,
  GardenCommunity,
  GardenSignalPool,
  SplitConfig,
  YieldAllocation,
  AllocateYieldParams,
  SetSplitRatioParams,
  // Contract types
  CreateGardenParams,
  DeploymentParams,
  NetworkContracts,
  // Blockchain types
  ChainId,
  DeploymentConfig,
  // Auth types
  AuthMode,
  BaseAuthContext,
  // Ops runner types
  OpsDeployRequest,
  OpsJob,
  OpsJobLogEntry,
  OpsJobLogsState,
  OpsJobStatus,
  OpsJobType,
  OpsRunScriptRequest,
  OpsRunnerChallengeResponse,
  OpsRunnerHealth,
  OpsRunnerJobResponse,
  OpsRunnerJobsResponse,
  OpsRunnerScriptDefinition,
  OpsRunnerScriptsResponse,
  OpsRunnerSession,
  OpsRunnerVerifyResponse,
  OpsUpgradeRequest,
} from "./types/index";

// Re-export enums and constants
export {
  ACTION_DOMAINS,
  LISTING_DEFAULTS,
  Capital,
  Confidence,
  CynefinPhase,
  Domain,
  DOMAIN_COLORS,
  VerificationMethod,
} from "./types/index";
export {
  WeightScheme,
  PoolType,
  WEIGHT_SCHEME_VALUES,
  DEFAULT_SPLIT_CONFIG,
  MIN_YIELD_THRESHOLD_USD,
} from "./types/index";
// ============================================================================
// UTILITIES
// ============================================================================
export type {
  CategorizedError,
  CategorizedErrorCategory,
  ClassValue,
  CompressionOptions,
  CompressionResult,
  CompressionStats,
  FormatAddressOptions,
  FormatAddressVariant,
  GardenMemberLike,
  GardenRole,
  NormalizeToFileOptions,
  ParsedContractError,
  Platform,
  PolymorphicComponent,
  PolymorphicComponentProps,
  PolymorphicComponentPropsWithRef,
  PolymorphicRef,
  Resolved,
  ResolveEnsAddressOptions,
  ResolveEnsOptions,
  SlugValidationResult,
  SimulationResult,
  Theme,
  TimeFilter,
  WorkData,
} from "./utils/index";
export {
  buildGardenMemberSets,
  calculateCompressionRatio,
  capitalize,
  categorizeError,
  clearFormDraft,
  cn,
  compareAddresses,
  copyToClipboard,
  DEBUG_ENABLED,
  debugError,
  debugLog,
  debugWarn,
  defaultTemplate,
  fetchOfflineWorks,
  formatAddress,
  formatDate,
  formatDateRange,
  formatDateTime,
  formatErrorForToast,
  formatFileSize,
  formatRelativeTime,
  fromDateInputValue,
  fromDateTimeLocalValue,
  expandDomainMask,
  GARDEN_ROLE_COLORS,
  GARDEN_ROLE_I18N_KEYS,
  GARDEN_ROLE_ORDER,
  GardenAccountABI,
  GardenTokenABI,
  HatsABI,
  gardenHasMember,
  getBlockchainErrorI18nKey,
  getEASExplorerUrl,
  getNetworkContracts,
  OCTANT_MODULE_ABI,
  getRoleColorClasses,
  getTag,
  hasDomain,
  hapticLight,
  hapticSelection,
  hapticSuccess,
  imageCompressor,
  initTheme,
  instructionTemplates,
  isAlreadyGardenerError,
  isValidAddressFormat,
  isValidAttestationId,
  loadFormDraft,
  normalizeToFile,
  openEASExplorer,
  extractErrorMessage,
  parseAndFormatError,
  parseContractError,
  recursiveCloneChildren,
  resolveEnsAddress,
  suggestSlug,
  validateSlug,
  saveFormDraft,
  toDateInputValue,
  toDateTimeLocalValue,
  toSafeDate,
  USER_FRIENDLY_ERRORS,
  ZERO_ADDRESS,
  validateDecimalInput,
  formatTokenAmount,
  getNetDeposited,
  getVaultAssetDecimals,
  getVaultAssetSymbol,
  hasVaultAssetDecimals,
  isZeroAddressValue,
  // Address utilities
  isAddressInList,
  isUserAddress,
  truncateAddress,
  // Action utilities
  findActionByUID,
  // Form normalizers
  normalizeTimeSpentMinutes,
  formatTimeSpent,
  // Work utilities
  convertJobsToWorks,
  downloadWorkData,
  downloadWorkMedia,
  shareWork,
  filterByTimeRange,
  // ABI exports
  GARDEN_ACCOUNT_ROLE_ABI,
} from "./utils/index";

// ============================================================================
// WORKFLOWS (re-export via subpath import recommended: @green-goods/shared/workflows)
// ============================================================================
export type { CreateGardenFormStatus } from "./workflows/index";
export { createGardenMachine } from "./workflows/index";
