// Main entry point for @green-goods/shared
// EXPLICIT EXPORTS for tree-shaking - organized by category

// ============================================================================
// COMPONENTS
// ============================================================================
export type {
  CenteredSpinnerProps,
  FormatMessageFn,
  FormInputProps,
  FormLayoutProps,
  FormTextareaProps,
  HydrationFallbackProps,
  SpinnerProps,
  StatusBadgeProps,
  ToastAction,
  ToastDescriptor,
  ToastHandle,
  ToastStatus,
  ToastTranslator,
  ToastViewportProps,
  WorkStatus,
} from "./components/index";
export {
  approvalToasts,
  CenteredSpinner,
  createApprovalToasts,
  createLocalizedToasts,
  createQueueToasts,
  createValidationToasts,
  createWalletProgressToasts,
  createWorkToasts,
  FormInput,
  FormLayout,
  FormTextarea,
  getStatusColors,
  HydrationFallback,
  queueToasts,
  Spinner,
  StatusBadge,
  setToastTranslator,
  showWalletProgress,
  ToastViewport,
  TranslationBadge,
  toastMessageIds,
  toastService,
  validationToasts,
  walletProgressToasts,
  workToasts,
} from "./components/index";

// ============================================================================
// CONFIG
// ============================================================================
export type {
  EASConfig,
  NetworkConfig,
  PasskeyServerClient,
  SupportedChainId,
} from "./config/index";
export {
  APP_DEFAULT_TITLE,
  APP_DESCRIPTION,
  APP_ICON,
  APP_NAME,
  APP_TITLE_TEMPLATE,
  APP_URL,
  appKit,
  createPasskeyServerClient,
  createPimlicoClientForChain,
  createPublicClientForChain,
  DEFAULT_CHAIN_ID,
  GC_TIMES,
  getChain,
  getChainName,
  getDefaultChain,
  getEASConfig,
  getEasGraphqlUrl,
  getIndexerUrl,
  getNetworkConfig,
  getPimlicoApiKey,
  getPimlicoBundlerUrl,
  getPimlicoPaymasterUrl,
  isChainSupported,
  isPasskeyServerAvailable,
  ONBOARDED_STORAGE_KEY,
  queryClient,
  STALE_TIMES,
  SUPPORTED_CHAINS,
  wagmiConfig,
} from "./config/index";

// ============================================================================
// HOOKS
// ============================================================================
export type {
  CreateAssessmentForm,
  DebugModeState,
  DeploymentRegistryPermissions,
  EnhancedWorkApproval,
  GardenerProfile,
  GardenInvite,
  GardenOperationConfig,
  GardenPermissions,
  QueryKey,
  QueueQueryKey,
  RoleInfo,
  ToastActionOptions,
  UseAnalyticsIdentityOptions,
  UsePageViewOptions,
  UserRole,
  WorkFormData,
  WorksQueryKey,
} from "./hooks/index";
export {
  checkGardenOpenJoining,
  checkMembership,
  createGardenOperation,
  ensureBaseLists,
  GARDEN_OPERATIONS,
  GardenTab,
  isGardenMember,
  jobToWork,
  queryInvalidation,
  queryKeys,
  useActionOperations,
  useActions,
  useActionTranslation,
  useAnalyticsIdentity,
  useAuth,
  useAutoJoinRootGarden,
  useBrowserNavigation,
  useChainConfig,
  useCreateAssessmentWorkflow,
  useCreateGardenWorkflow,
  useCurrentChain,
  useDebugMode,
  useDeploymentRegistry,
  useEASConfig,
  useEnsAddress,
  useEnsAvatar,
  useEnsName,
  useGardenAssessments,
  useGardenerProfile,
  useGardeners,
  useGardenInvites,
  useGardenOperations,
  useGardenPermissions,
  useGardens,
  useGardenTabs,
  useGardenTranslation,
  useJoinGarden,
  useMerged,
  useMyOnlineWorks,
  useMyWorks,
  useNavigateToTop,
  useNetworkConfig,
  useOffline,
  usePageView,
  usePendingWorksCount,
  useQueueStatistics,
  useRole,
  useScrollReveal,
  useTheme,
  useToastAction,
  useTranslation,
  useUser,
  useWorkApproval,
  useWorkApprovals,
  useWorkForm,
  useWorkImages,
  useWorkMutation,
  useWorks,
  workFormSchema,
} from "./hooks/index";
// ============================================================================
// I18N
// ============================================================================
export { en, es, pt } from "./i18n/index";
// ============================================================================
// MODULES
// ============================================================================
export type {
  FragmentOf,
  PasskeyApprovalSubmissionParams,
  PasskeyWorkSubmissionParams,
  ResultOf,
  VariablesOf,
} from "./modules/index";
export {
  // Session management
  AUTH_MODE_STORAGE_KEY,
  browserTranslator,
  clearAllAuth,
  clearAuthMode,
  clearStoredPasskey,
  clearStoredUsername,
  createEasClient,
  createIndexerClient,
  createOfflineTxHash,
  easGraphQL,
  formatJobError,
  getActions,
  getAuthMode,
  getDistinctId,
  getFileByHash,
  getGardenAssessments,
  getGardeners,
  getGardens,
  getStoredUsername,
  getSubmissionStatusText,
  getWorkApprovals,
  getWorks,
  getWorksByGardener,
  greenGoodsGraphQL,
  greenGoodsIndexer,
  hasStoredPasskey,
  hasStoredUsername,
  identify,
  identifyWithProperties,
  initializeIpfs,
  initializeIpfsFromEnv,
  initializePinata,
  initializePinataFromEnv,
  jobQueue,
  jobQueueDB,
  jobQueueEventBus,
  PASSKEY_STORAGE_KEY,
  reset,
  resolveAvatarUrl,
  resolveImageUrl,
  resolveIPFSUrl,
  runTranslationDiagnostics,
  serviceWorkerManager,
  setAuthMode,
  setStoredUsername,
  submitApprovalBot,
  submitApprovalWithPasskey,
  submitWorkBot,
  submitWorkWithPasskey,
  track,
  trackAppLifecycle,
  trackOfflineEvent,
  trackSyncPerformance,
  translationCache,
  USERNAME_STORAGE_KEY,
  updateUserProfile,
  uploadFileToIPFS,
  uploadJSONToIPFS,
  useJobQueueEvents,
  validateApprovalDraft,
  validateWorkDraft,
} from "./modules/index";
// ============================================================================
// PROVIDERS (re-export via subpath import recommended: @green-goods/shared/providers)
// ============================================================================
export type { AuthContextType } from "./providers/index";
export {
  AppKitProvider,
  AppProvider,
  // Unified auth provider (supports both passkey and wallet)
  AuthProvider,
  // Job Queue & Work
  JobQueueProvider,
  useApp,
  useAppKit,
  useAuthContext,
  useJobQueue,
  useWork,
  WorkProvider,
} from "./providers/index";
// ============================================================================
// STORES (re-export via subpath import recommended: @green-goods/shared/stores)
// ============================================================================
export {
  type AdminState,
  type CreateGardenFormState,
  type CreateGardenStep,
  type UIState,
  useAdminStore,
  useCreateGardenStore,
  useUIStore,
  useWorkFlowStore,
  type WorkDraftState,
  type WorkFlowState,
  WorkTab,
} from "./stores/index";
// ============================================================================
// TYPES
// ============================================================================
export type {
  // Domain types
  Address,
  GardenerCard,
  GardenCard,
  Garden,
  PlantInfo,
  SpeciesRegistry,
  GardenAssessment,
  AssessmentDraft,
  ActionCard,
  Action,
  WorkInput,
  WorkDraft,
  WorkCard,
  Work,
  WorkMetadata,
  WorkApprovalDraft,
  WorkApproval,
  ActionInstructionConfig,
  Link,
  // Job queue types
  Job,
  QueueEvent,
  JobProcessor,
  WorkJobPayload,
  ApprovalJobPayload,
  JobKindMap,
  JobKind,
  JobPayload,
  QueueSubscriber,
  QueueStats,
  JobQueueDBImage,
  CachedWork,
  // Offline types
  OfflineStatus,
  OfflineDashboardData,
  OfflineWorkItem,
  SyncMetrics,
  OfflineSettings,
  OfflineCapabilities,
  WorkConflict,
  DuplicateCheckResult,
  // Indexer response types
  IndexerGarden,
  IndexerGardensResponse,
  IndexerAction,
  IndexerActionsResponse,
  IndexerGardener,
  IndexerGardenersResponse,
  // EAS response types
  EASAttestationRaw,
  EASAttestationsResponse,
  EASDecodedField,
  EASGardenAssessment,
  EASWork,
  EASWorkApproval,
  // Contract types
  CreateGardenParams,
  DeploymentParams,
  NetworkContracts,
  // Blockchain types
  ChainId,
  DeploymentConfig,
  // Auth types
  AuthMode,
  BaseAuthContext,
} from "./types/index";

// Re-export Capital enum
export { Capital } from "./types/index";
// ============================================================================
// UTILITIES
// ============================================================================
export type {
  ClassValue,
  CompressionOptions,
  CompressionResult,
  CompressionStats,
  FormatAddressOptions,
  FormatAddressVariant,
  GardenMemberLike,
  NormalizeToFileOptions,
  ParsedContractError,
  PolymorphicComponent,
  PolymorphicComponentProps,
  PolymorphicComponentPropsWithRef,
  PolymorphicRef,
  Resolved,
  ResolveEnsAddressOptions,
  ResolveEnsOptions,
  SimulationResult,
  Theme,
  TimeFilter,
  WorkData,
} from "./utils/index";
export {
  ActionRegistryABI,
  buildApprovalAttestTx,
  buildGardenMemberSets,
  buildWorkAttestTx,
  calculateCompressionRatio,
  capitalize,
  clearFormDraft,
  cn,
  compareAddresses,
  convertJobsToWorks,
  copyToClipboard,
  createClients,
  createDispatchAdapter,
  DEBUG_ENABLED,
  debugError,
  debugLog,
  debugWarn,
  deduplicateById,
  defaultTemplate,
  downloadWorkData,
  encodeWorkApprovalData,
  extractClientWorkId,
  fetchOfflineWorks,
  filterByTimeRange,
  formatAddress,
  formatDate,
  formatDateTime,
  formatErrorForToast,
  formatFileSize,
  formatRelativeTime,
  formatUserError,
  formatWalletError,
  fromDateTimeLocalValue,
  GardenAccountABI,
  GardenTokenABI,
  gardenHasMember,
  getBlockExplorerTxUrl,
  getEASExplorerUrl,
  getNetworkContracts,
  getResolvedTheme,
  getTag,
  getTheme,
  getTimeCutoff,
  imageCompressor,
  initTheme,
  instructionTemplates,
  isAddressInList,
  isAlreadyGardenerError,
  isNotGardenerError,
  isUserAddress,
  isValidAddressFormat,
  isValidAttestationId,
  listenToSystemChanges,
  loadFormDraft,
  mergeAndDeduplicateByClientId,
  normalizeAddress,
  normalizeToFile,
  openBlockExplorerTx,
  openEASExplorer,
  parseAndFormatError,
  parseContractError,
  pollQueriesAfterTransaction,
  pollQueryAfterTransaction,
  recursiveCloneChildren,
  resolveEnsAddress,
  resolveEnsName,
  resolveGardenMemberKey,
  saveFormDraft,
  setTheme,
  simulateJoinGarden,
  simulateTransaction,
  sortByCreatedAt,
  toDateTimeLocalValue,
  toggle,
  toSafeDate,
  truncate,
  truncateAddress,
  USER_FRIENDLY_ERRORS,
} from "./utils/index";

// ============================================================================
// WORKFLOWS (re-export via subpath import recommended: @green-goods/shared/workflows)
// ============================================================================
export {
  // Assessment
  type AssessmentContext,
  type AssessmentEvent,
  // Auth Actor
  type AuthActor,
  // Auth (XState Machine)
  type AuthContext,
  type AuthEvent,
  type AuthMachine,
  type AuthSnapshot,
  type AuthState,
  authActor,
  authenticatePasskeyService,
  authMachine,
  authSelectors,
  // Auth Services
  authServices,
  // Garden
  type CreateGardenContext,
  type CreateGardenEvent,
  claimENSService,
  createAssessmentMachine,
  createGardenMachine,
  getAuthActor,
  type PasskeySessionResult,
  type RestoreSessionResult,
  registerPasskeyService,
  restoreSessionService,
} from "./workflows/index";
