// Generates handoffs/commitment-view-state-reference.md from the live tables.
//
// The reference is GENERATED rather than written because a hand-kept table of
// "which seat does this state belong to" would be a sixth derivation of the same
// fact, and the 2026-08-18 round exists precisely because five of them had
// drifted apart. If the tables move, this file moves with them or the diff shows.
//
//   bun .plans/active/commitment-pooling/hifi/state-reference.gen.ts
//
// Re-run it in the same change as any W2 state addition, and commit the output.

import { writeFileSync } from "node:fs";
import { w2SeatReference } from "./screens/client";

const rows = w2SeatReference();
const OUT = new URL("../handoffs/commitment-view-state-reference.md", import.meta.url);

const count = <T extends string>(key: (r: (typeof rows)[number]) => T) => {
  const m: Record<string, number> = {};
  for (const r of rows) m[key(r)] = (m[key(r)] ?? 0) + 1;
  return Object.entries(m).sort((a, b) => b[1] - a[1]);
};
const tally = (pairs: [string, number][]) => pairs.map(([k, v]) => `${k} ${v}`).join(" · ");

const acts = rows.filter((r) => r.bar);
const seatMismatch = acts.filter((r) => r.bar !== r.seat);

const body = `<!-- GENERATED by hifi/state-reference.gen.ts — do not edit by hand. -->

# The commitment view: state reference

The implementation contract for \`W2\`, the commitment detail screen. Generated from the
prototype's own tables, so it cannot drift from what the artifact draws.

**Regenerate with** \`bun .plans/active/commitment-pooling/hifi/state-reference.gen.ts\` and commit
the output in the same change as any state addition.

## The three axes

A commitment screen is decided by three facts, and only three:

- **cast** — what kind of commitment this is. Derivable from the record: kind plus direction.
- **phase** — where it sits in the contract lifecycle. \`deriveCommitmentState()\` already returns
  this, and the values below are exactly its vocabulary.
- **seat** — who is reading. **This is the one the shared layer cannot currently express.** See
  \`handoffs/codex-state-api.md\` § Seat.

### Creator is not a seat

Four seats are enough because direction already names the creator: on an Offer the creator is the
provider, on a Request the creator is the confirmer. So a pre-acceptance Offer is a provider's
screen and a pre-acceptance Request is a confirmer's, and the withdraw affordance gates on *phase*
(nobody has taken it up yet) while seat only decides the person of the sentence.

Implementations that add a fifth "creator" seat will find it collides with provider and confirmer
on every state, which is how the prototype's own people table came to contradict itself.

### What each seat means

| Seat | Who | May act |
|---|---|---|
| \`provider\` | does the work | add proof, submit and link work, send for confirmation, withdraw pre-acceptance |
| \`confirmer\` | receives it and says it was kept | confirm, say not yet, withdraw a request pre-acceptance |
| \`contributor\` | on the team, not the lead | add proof, submit work. Never confirms, never sends |
| \`bystander\` | no relationship yet | take it up, ask to take it up, join an open team |

## Distribution

- **${rows.length} states** (the three read surfaces carry no axes and are excluded)
- seat — ${tally(count((r) => r.seat))}
- cast — ${tally(count((r) => r.cast))}
- phase — ${tally(count((r) => r.phase))}
- **${acts.length} states carry an act.** ${
  seatMismatch.length === 0
    ? "Every one belongs to the seat reading that screen; the build refuses otherwise."
    : `${seatMismatch.length} disagree with their state's seat, which should be impossible — the build check has regressed.`
}

## Every state

\`bar\` names the seat whose act sits in the fixed bottom bar. A blank means the screen is a read
surface for that seat: there is nothing for this person to do here, which is a deliberate answer
rather than a missing one.

| State | Cast | Seat | Phase | Bar | Frame group |
|---|---|---|---|---|---|
${rows.map((r) => `| \`${r.state}\` | ${r.cast} | **${r.seat}** | ${r.phase} | ${r.bar ?? "—"} | ${r.group} |`).join("\n")}

## Reading this as an implementer

1. **Do not infer seat from the state id.** The ids encode lifecycle and cast, and only sometimes
   seat (\`ready-confirmer\` says it, \`requested\` does not). Every defect the 2026-08-18 audit found
   on this screen came from inferring it.
2. **Phase decides affordances, seat decides person.** Whether withdrawal is offered at all is a
   phase question. Whether the sentence reads "you can withdraw it" or "whoever made this can
   withdraw it" is a seat question.
3. **Two seats on one stage means two states.** Where a lifecycle position needs both a provider's
   and a confirmer's view, the prototype adds a state rather than branching inside one
   (\`active\` / \`active-waiting\`, \`ready-provider\` / \`ready-confirmer\`). \`W4@provider-view\` is the
   shipped precedent: same stage, same facts, no bar.
4. **A seat with no act gets no bar**, not a disabled one. The provider on a ready commitment is
   asking "where has this got to?", and a greyed-out Confirm answers a question they did not ask.
`;

writeFileSync(OUT, body);
console.log(`state reference: ${rows.length} states · ${acts.length} with acts · ${seatMismatch.length} seat mismatches`);
console.log(`→ ${OUT.pathname}`);
